import type { ModuleInjectionTable } from '@open-mercato/shared/modules/widgets/injection'
import { translatableFields as catalogFields } from '../../catalog/translations'
import { translatableFields as dictionaryFields } from '../../dictionaries/translations'
import { translatableFields as entitiesFields } from '../../entities/translations'
import { translatableFields as resourcesFields } from '../../resources/translations'

const WIDGET_ID = 'translations.injection.translation-manager'

const allFields: Record<string, string[]> = {
  ...catalogFields,
  ...dictionaryFields,
  ...entitiesFields,
  ...resourcesFields,
}

const ENTRY_TEMPLATE = {
  widgetId: WIDGET_ID,
  kind: 'group' as const,
  column: 2 as const,
  groupLabel: 'translations.widgets.translationManager.groupLabel',
  groupDescription: 'translations.widgets.translationManager.groupDescription',
  priority: 40,
}

const table: ModuleInjectionTable = {}
for (const entityType of Object.keys(allFields)) {
  const [module, entitySlug] = entityType.split(':')
  if (!module || !entitySlug) continue

  // Full form: crud-form:catalog.catalog_product (auto-generated by CrudForm from entityId)
  const fullSpot = `crud-form:${module}.${entitySlug}`
  table[fullSpot] = [{ ...ENTRY_TEMPLATE }]

  // Short form: crud-form:catalog.product (hardcoded in some pages)
  const prefix = `${module}_`
  if (entitySlug.startsWith(prefix)) {
    const shortSpot = `crud-form:${module}.${entitySlug.slice(prefix.length)}`
    if (shortSpot !== fullSpot) {
      table[shortSpot] = [{ ...ENTRY_TEMPLATE }]
    }
  }
}

export const injectionTable: ModuleInjectionTable = table
export default injectionTable
