compressionLevel: mixed

enableTelemetry: false

nodeLinker: node-modules

npmRegistryServer: "https://registry.npmjs.org"
npmPublishRegistry: "https://registry.npmjs.org"

packageExtensions:
  "cmdk@*":
    peerDependenciesMeta:
      react:
        optional: true
      react-dom:
        optional: true
      "@types/react":
        optional: true
  "ts-jest@*":
    peerDependenciesMeta:
      typescript:
        optional: true
  "@radix-ui/react-tooltip@*":
    peerDependenciesMeta:
      react:
        optional: true
      react-dom:
        optional: true
  "@testing-library/react@*":
    peerDependenciesMeta:
      react:
        optional: true
      react-dom:
        optional: true
  "react-big-calendar@*":
    peerDependenciesMeta:
      react:
        optional: true
      react-dom:
        optional: true
  "@algolia/autocomplete-shared@*":
    peerDependenciesMeta:
      "@algolia/client-search":
        optional: true
      algoliasearch:
        optional: true
  "@algolia/autocomplete-plugin-algolia-insights@*":
    peerDependenciesMeta:
      search-insights:
        optional: true
  "@docusaurus/core@*":
    peerDependenciesMeta:
      "@mdx-js/react":
        optional: true
      react:
        optional: true
      react-dom:
        optional: true
  "@docusaurus/types@*":
    peerDependenciesMeta:
      react:
        optional: true
      react-dom:
        optional: true
  "@docusaurus/mdx-loader@*":
    peerDependenciesMeta:
      react:
        optional: true
      react-dom:
        optional: true
  "@docusaurus/theme-common@*":
    peerDependenciesMeta:
      "@docusaurus/plugin-content-docs":
        optional: true
  "@docusaurus/react-loadable@*":
    peerDependenciesMeta:
      react:
        optional: true
  "@slorber/react-helmet-async@*":
    peerDependenciesMeta:
      react:
        optional: true
      react-dom:
        optional: true
  "react-router@*":
    peerDependenciesMeta:
      react:
        optional: true
  "react-router-config@*":
    peerDependenciesMeta:
      react:
        optional: true
  "react-router-dom@*":
    peerDependenciesMeta:
      react:
        optional: true
      react-dom:
        optional: true
  "@react-email/render@*":
    peerDependenciesMeta:
      react-dom:
        optional: true
  "ai-sdk-ollama@*":
    dependencies:
      zod: "^4.3.6"
