import fs from 'node:fs'
import path from 'node:path'
import os from 'node:os'
import type { PackageResolver, ModuleEntry } from '../../resolver'
import { generateModuleRegistry, generateModuleRegistryApp, generateModuleRegistryCli } from '../module-registry'

let tmpDir: string
let fileMtimeNonce = 0

function createTmpDir(): string {
  return fs.mkdtempSync(path.join(os.tmpdir(), 'module-subset-test-'))
}

function touchFile(filePath: string, content = ''): void {
  fs.mkdirSync(path.dirname(filePath), { recursive: true })
  fs.writeFileSync(filePath, content)
  const mtime = new Date(Date.now() + fileMtimeNonce)
  fileMtimeNonce += 1
  fs.utimesSync(filePath, mtime, mtime)
}

function scaffoldModule(
  tmpDir: string,
  modId: string,
  location: 'pkg' | 'app',
  files: string[]
): void {
  const base =
    location === 'pkg'
      ? path.join(tmpDir, 'packages', 'core', 'src', 'modules', modId)
      : path.join(tmpDir, 'app', 'src', 'modules', modId)
  for (const file of files) {
    touchFile(path.join(base, file))
  }
}

function createMockResolver(
  tmpDir: string,
  enabled: ModuleEntry[]
): PackageResolver {
  const outputDir = path.join(tmpDir, 'output', 'generated')
  fs.mkdirSync(outputDir, { recursive: true })

  return {
    isMonorepo: () => true,
    getRootDir: () => tmpDir,
    getAppDir: () => path.join(tmpDir, 'app'),
    getOutputDir: () => outputDir,
    getModulesConfigPath: () => path.join(tmpDir, 'app', 'src', 'modules.ts'),
    discoverPackages: () => [],
    loadEnabledModules: () => enabled,
    getModulePaths: (entry: ModuleEntry) => ({
      appBase: path.join(tmpDir, 'app', 'src', 'modules', entry.id),
      pkgBase: path.join(
        tmpDir,
        'packages',
        'core',
        'src',
        'modules',
        entry.id
      ),
    }),
    getModuleImportBase: (entry: ModuleEntry) => ({
      appBase: `@/modules/${entry.id}`,
      pkgBase: `@open-mercato/core/modules/${entry.id}`,
    }),
    getPackageOutputDir: () => outputDir,
    getPackageRoot: () => path.join(tmpDir, 'packages', 'core'),
  }
}

function createStandaloneMockResolver(
  tmpDir: string,
  enabled: ModuleEntry[]
): PackageResolver {
  const outputDir = path.join(tmpDir, '.mercato', 'generated')
  fs.mkdirSync(outputDir, { recursive: true })

  return {
    isMonorepo: () => false,
    getRootDir: () => tmpDir,
    getAppDir: () => tmpDir,
    getOutputDir: () => outputDir,
    getModulesConfigPath: () => path.join(tmpDir, 'src', 'modules.ts'),
    discoverPackages: () => [],
    loadEnabledModules: () => enabled,
    getModulePaths: (entry: ModuleEntry) => ({
      appBase: path.join(tmpDir, 'src', 'modules', entry.id),
      pkgBase: path.join(
        tmpDir,
        'node_modules',
        'pkg',
        'dist',
        'modules',
        entry.id
      ),
    }),
    getModuleImportBase: (entry: ModuleEntry) => ({
      appBase: `@/modules/${entry.id}`,
      pkgBase: `@open-mercato/core/modules/${entry.id}`,
    }),
    getPackageOutputDir: () => outputDir,
    getPackageRoot: () => path.join(tmpDir, 'node_modules', 'pkg'),
  }
}

function readGenerated(tmpDir: string, filename: string): string | null {
  const filePath = path.join(tmpDir, 'output', 'generated', filename)
  if (!fs.existsSync(filePath)) return null
  return fs.readFileSync(filePath, 'utf8')
}

function dedent(value: string): string {
  const normalized = value.replace(/^\n/, '')
  const lines = normalized.split('\n')
  const nonEmptyLines = lines.filter((line) => line.trim().length > 0)
  const indent = nonEmptyLines.length > 0
    ? Math.min(...nonEmptyLines.map((line) => line.match(/^ */)?.[0].length ?? 0))
    : 0

  return lines.map((line) => line.slice(indent)).join('\n')
}

// Inline CommonJS generators.ts that provides the security generator plugins.
// Written as plain JS (no TypeScript) so it can be dynamically imported from tmpDir
// without ts-jest transpilation.
const SECURITY_GENERATORS_CONTENT = `'use strict'
function buildMfaOutput({ importSection, entriesLiteral }) {
  return '// AUTO-GENERATED by mercato generate registry\\n'
    + (importSection ? importSection + '\\n' : '')
    + 'type SecurityMfaProviderEntry = { moduleId: string; providers: unknown[] }\\n\\n'
    + 'export const securityMfaProviderEntries: SecurityMfaProviderEntry[] = [\\n'
    + (entriesLiteral ? '  ' + entriesLiteral + '\\n' : '')
    + ']\\n'
}
function buildSudoOutput({ importSection, entriesLiteral }) {
  return '// AUTO-GENERATED by mercato generate registry\\n'
    + "import type { SecuritySudoTarget, SecuritySudoTargetEntry } from '@open-mercato/enterprise/modules/security'\\n"
    + (importSection ? '\\n' + importSection + '\\n' : '\\n') + '\\n'
    + 'type SecuritySudoTargetEntryRaw = { moduleId: string; targets: Array<Record<string, unknown>> }\\n\\n'
    + 'const entriesRaw: SecuritySudoTargetEntryRaw[] = [\\n'
    + (entriesLiteral ? '  ' + entriesLiteral + '\\n' : '')
    + ']\\n\\n'
    + 'export const securitySudoTargetEntries: SecuritySudoTargetEntry[] = entriesRaw.map(function(e) { return { moduleId: e.moduleId, targets: e.targets } })\\n'
}
module.exports = {
  generatorPlugins: [
    {
      id: 'security.mfa-providers',
      conventionFile: 'security.mfa-providers.ts',
      importPrefix: 'SECURITY_MFA_PROVIDERS',
      configExpr: function(n, id) { return "{ moduleId: '" + id + "', providers: ((" + n + ".default ?? " + n + ".mfaProviders ?? []) as unknown[]) }" },
      outputFileName: 'security-mfa-providers.generated.ts',
      buildOutput: buildMfaOutput,
    },
    {
      id: 'security.sudo',
      conventionFile: 'security.sudo.ts',
      importPrefix: 'SECURITY_SUDO',
      configExpr: function(n, id) { return "{ moduleId: '" + id + "', targets: ((" + n + ".default ?? " + n + ".sudoTargets ?? []) as Array<Record<string, unknown>>) }" },
      outputFileName: 'security-sudo.generated.ts',
      buildOutput: buildSudoOutput,
    },
  ],
}
`

beforeEach(() => {
  tmpDir = createTmpDir()
  fileMtimeNonce = 0
})

afterEach(() => {
  fs.rmSync(tmpDir, { recursive: true, force: true })
})

describe('generateModuleRegistry with module subsets', () => {
  it('generates valid output with zero modules enabled', async () => {
    const resolver = createMockResolver(tmpDir, [])
    const result = await generateModuleRegistry({ resolver, quiet: true })

    expect(result.errors).toEqual([])
    const output = readGenerated(tmpDir, 'modules.generated.ts')
    expect(output).not.toBeNull()
    expect(output).toContain('export const modules: Module[] = [')
    expect(output).toContain('export default modules')
  })

  it('preserves exact legacy empty output format for the refactored registry files', async () => {
    const resolver = createMockResolver(tmpDir, [])
    const result = await generateModuleRegistry({ resolver, quiet: true })

    expect(result.errors).toEqual([])
    expect(readGenerated(tmpDir, 'modules.generated.ts')).toBe(dedent(`
      // AUTO-GENERATED by mercato generate registry
      import { createLazyModuleSubscriber, createLazyModuleWorker, type Module } from '@open-mercato/shared/modules/registry'

      export const modules: Module[] = [
        
      ]
      export const modulesInfo = modules.map(m => ({ id: m.id, ...(m.info || {}) }))
      export default modules
    `))
    expect(readGenerated(tmpDir, 'modules.runtime.generated.ts')).toBe(dedent(`
      // AUTO-GENERATED by mercato generate registry
      import { createElement } from 'react'
      import { createLazyModuleSubscriber, createLazyModuleWorker, type Module } from '@open-mercato/shared/modules/registry'

      export const modules: Module[] = [
        
      ]
      export const modulesInfo = modules.map(m => ({ id: m.id, ...(m.info || {}) }))
      export default modules
    `))
    expect(readGenerated(tmpDir, 'frontend-routes.generated.ts')).toBe(dedent(`
      // AUTO-GENERATED by mercato generate registry
      import type { FrontendRouteManifestEntry } from '@open-mercato/shared/modules/registry'

      export const frontendRoutes: FrontendRouteManifestEntry[] = [
        
      ]

      export default frontendRoutes
    `))
    expect(readGenerated(tmpDir, 'backend-routes.generated.ts')).toBe(dedent(`
      // AUTO-GENERATED by mercato generate registry
      import type { BackendRouteManifestEntry } from '@open-mercato/shared/modules/registry'

      export const backendRoutes: BackendRouteManifestEntry[] = [
        
      ]

      export default backendRoutes
    `))
    expect(readGenerated(tmpDir, 'api-routes.generated.ts')).toBe(dedent(`
      // AUTO-GENERATED by mercato generate registry
      import type { ApiRouteManifestEntry } from '@open-mercato/shared/modules/registry'

      export const apiRoutes: ApiRouteManifestEntry[] = [
        
      ]

      export default apiRoutes
    `))
  })

  it('preserves exact legacy populated output format for the refactored registry files', async () => {
    touchFile(
      path.join(tmpDir, 'packages', 'core', 'src', 'modules', 'orders', 'index.ts'),
      "export const metadata = { id: 'orders', label: 'Orders' }\n",
    )
    touchFile(
      path.join(tmpDir, 'packages', 'core', 'src', 'modules', 'orders', 'frontend', 'page.tsx'),
      'export default function OrdersPage() { return null }\n',
    )
    touchFile(
      path.join(tmpDir, 'packages', 'core', 'src', 'modules', 'orders', 'backend', 'page.tsx'),
      'export default function OrdersBackendPage() { return null }\n',
    )
    touchFile(
      path.join(tmpDir, 'packages', 'core', 'src', 'modules', 'orders', 'api', 'orders', 'route.ts'),
      "export function GET() { return new Response('ok') }\n",
    )

    const resolver = createMockResolver(tmpDir, [{ id: 'orders', from: '@open-mercato/core' }])
    const result = await generateModuleRegistry({ resolver, quiet: true })

    expect(result.errors).toEqual([])
    expect(readGenerated(tmpDir, 'modules.generated.ts')).toBe(dedent(`
      // AUTO-GENERATED by mercato generate registry
      import { createLazyModuleSubscriber, createLazyModuleWorker, type Module } from '@open-mercato/shared/modules/registry'
      import * as I0_orders from "@open-mercato/core/modules/orders/index"
      import C1_orders_index, * as CM2_orders_index from "@open-mercato/core/modules/orders/frontend/page"
      import B5_orders_index, * as BM6_orders_index from "@open-mercato/core/modules/orders/backend/page"
      import * as R9_orders_orders from "@open-mercato/core/modules/orders/api/orders/route"

      export const modules: Module[] = [
        {
            id: "orders",
            info: I0_orders.metadata,
            frontendRoutes: [{ pattern: "/", requireAuth: ((CM2_orders_index as any).metadata)?.requireAuth, requireRoles: ((CM2_orders_index as any).metadata)?.requireRoles, requireFeatures: ((CM2_orders_index as any).metadata)?.requireFeatures, requireCustomerAuth: ((CM2_orders_index as any).metadata)?.requireCustomerAuth, requireCustomerFeatures: ((CM2_orders_index as any).metadata)?.requireCustomerFeatures, nav: ((CM2_orders_index as any).metadata)?.nav, title: ((CM2_orders_index as any).metadata)?.pageTitle ?? ((CM2_orders_index as any).metadata)?.title, titleKey: ((CM2_orders_index as any).metadata)?.pageTitleKey ?? ((CM2_orders_index as any).metadata)?.titleKey, group: ((CM2_orders_index as any).metadata)?.pageGroup ?? ((CM2_orders_index as any).metadata)?.group, groupKey: ((CM2_orders_index as any).metadata)?.pageGroupKey ?? ((CM2_orders_index as any).metadata)?.groupKey, icon: ((CM2_orders_index as any).metadata)?.icon, order: ((CM2_orders_index as any).metadata)?.pageOrder ?? ((CM2_orders_index as any).metadata)?.order, priority: ((CM2_orders_index as any).metadata)?.pagePriority ?? ((CM2_orders_index as any).metadata)?.priority, navHidden: ((CM2_orders_index as any).metadata)?.navHidden, visible: ((CM2_orders_index as any).metadata)?.visible, enabled: ((CM2_orders_index as any).metadata)?.enabled, breadcrumb: ((CM2_orders_index as any).metadata)?.breadcrumb, pageContext: ((CM2_orders_index as any).metadata)?.pageContext, placement: ((CM2_orders_index as any).metadata)?.placement, Component: C1_orders_index }],
            backendRoutes: [{ pattern: "/backend/orders", requireAuth: ((BM6_orders_index as any).metadata)?.requireAuth, requireRoles: ((BM6_orders_index as any).metadata)?.requireRoles, requireFeatures: ((BM6_orders_index as any).metadata)?.requireFeatures, requireCustomerAuth: ((BM6_orders_index as any).metadata)?.requireCustomerAuth, requireCustomerFeatures: ((BM6_orders_index as any).metadata)?.requireCustomerFeatures, nav: ((BM6_orders_index as any).metadata)?.nav, title: ((BM6_orders_index as any).metadata)?.pageTitle ?? ((BM6_orders_index as any).metadata)?.title, titleKey: ((BM6_orders_index as any).metadata)?.pageTitleKey ?? ((BM6_orders_index as any).metadata)?.titleKey, group: ((BM6_orders_index as any).metadata)?.pageGroup ?? ((BM6_orders_index as any).metadata)?.group, groupKey: ((BM6_orders_index as any).metadata)?.pageGroupKey ?? ((BM6_orders_index as any).metadata)?.groupKey, icon: ((BM6_orders_index as any).metadata)?.icon, order: ((BM6_orders_index as any).metadata)?.pageOrder ?? ((BM6_orders_index as any).metadata)?.order, priority: ((BM6_orders_index as any).metadata)?.pagePriority ?? ((BM6_orders_index as any).metadata)?.priority, navHidden: ((BM6_orders_index as any).metadata)?.navHidden, visible: ((BM6_orders_index as any).metadata)?.visible, enabled: ((BM6_orders_index as any).metadata)?.enabled, breadcrumb: ((BM6_orders_index as any).metadata)?.breadcrumb, pageContext: ((BM6_orders_index as any).metadata)?.pageContext, placement: ((BM6_orders_index as any).metadata)?.placement, Component: B5_orders_index }],
            apis: [{ path: ((R9_orders_orders as any).metadata?.path ?? "/orders/orders"), metadata: (R9_orders_orders as any).metadata, handlers: R9_orders_orders as any }],
            
            
            
            
            
            customFieldSets: [],
            
            
            
            
            
            
            
          }
      ]
      export const modulesInfo = modules.map(m => ({ id: m.id, ...(m.info || {}) }))
      export default modules
    `))
    expect(readGenerated(tmpDir, 'modules.runtime.generated.ts')).toBe(dedent(`
      // AUTO-GENERATED by mercato generate registry
      import { createElement } from 'react'
      import { createLazyModuleSubscriber, createLazyModuleWorker, type Module } from '@open-mercato/shared/modules/registry'
      import * as I0_orders from "@open-mercato/core/modules/orders/index"
      import * as MRuntime3_orders_index from "@open-mercato/core/modules/orders/frontend/page"
      import * as BMRuntime7_orders_index from "@open-mercato/core/modules/orders/backend/page"

      export const modules: Module[] = [
        {
            id: "orders",
            info: I0_orders.metadata,
            frontendRoutes: [{ pattern: "/", requireAuth: ((((MRuntime3_orders_index as any).metadata) as any))?.requireAuth, requireRoles: ((((MRuntime3_orders_index as any).metadata) as any))?.requireRoles, requireFeatures: ((((MRuntime3_orders_index as any).metadata) as any))?.requireFeatures, requireCustomerAuth: ((((MRuntime3_orders_index as any).metadata) as any))?.requireCustomerAuth, requireCustomerFeatures: ((((MRuntime3_orders_index as any).metadata) as any))?.requireCustomerFeatures, nav: ((((MRuntime3_orders_index as any).metadata) as any))?.nav, title: ((((MRuntime3_orders_index as any).metadata) as any))?.pageTitle ?? ((((MRuntime3_orders_index as any).metadata) as any))?.title, titleKey: ((((MRuntime3_orders_index as any).metadata) as any))?.pageTitleKey ?? ((((MRuntime3_orders_index as any).metadata) as any))?.titleKey, group: ((((MRuntime3_orders_index as any).metadata) as any))?.pageGroup ?? ((((MRuntime3_orders_index as any).metadata) as any))?.group, groupKey: ((((MRuntime3_orders_index as any).metadata) as any))?.pageGroupKey ?? ((((MRuntime3_orders_index as any).metadata) as any))?.groupKey, icon: ((((MRuntime3_orders_index as any).metadata) as any))?.icon, order: ((((MRuntime3_orders_index as any).metadata) as any))?.pageOrder ?? ((((MRuntime3_orders_index as any).metadata) as any))?.order, priority: ((((MRuntime3_orders_index as any).metadata) as any))?.pagePriority ?? ((((MRuntime3_orders_index as any).metadata) as any))?.priority, navHidden: ((((MRuntime3_orders_index as any).metadata) as any))?.navHidden, visible: ((((MRuntime3_orders_index as any).metadata) as any))?.visible, enabled: ((((MRuntime3_orders_index as any).metadata) as any))?.enabled, breadcrumb: ((((MRuntime3_orders_index as any).metadata) as any))?.breadcrumb, pageContext: ((((MRuntime3_orders_index as any).metadata) as any))?.pageContext, placement: ((((MRuntime3_orders_index as any).metadata) as any))?.placement, Component: async (props: any) => { const mod = await import("@open-mercato/core/modules/orders/frontend/page"); const Component = (mod.default ?? mod) as any; return createElement(Component, props) } }],
            backendRoutes: [{ pattern: "/backend/orders", requireAuth: ((((BMRuntime7_orders_index as any).metadata) as any))?.requireAuth, requireRoles: ((((BMRuntime7_orders_index as any).metadata) as any))?.requireRoles, requireFeatures: ((((BMRuntime7_orders_index as any).metadata) as any))?.requireFeatures, requireCustomerAuth: ((((BMRuntime7_orders_index as any).metadata) as any))?.requireCustomerAuth, requireCustomerFeatures: ((((BMRuntime7_orders_index as any).metadata) as any))?.requireCustomerFeatures, nav: ((((BMRuntime7_orders_index as any).metadata) as any))?.nav, title: ((((BMRuntime7_orders_index as any).metadata) as any))?.pageTitle ?? ((((BMRuntime7_orders_index as any).metadata) as any))?.title, titleKey: ((((BMRuntime7_orders_index as any).metadata) as any))?.pageTitleKey ?? ((((BMRuntime7_orders_index as any).metadata) as any))?.titleKey, group: ((((BMRuntime7_orders_index as any).metadata) as any))?.pageGroup ?? ((((BMRuntime7_orders_index as any).metadata) as any))?.group, groupKey: ((((BMRuntime7_orders_index as any).metadata) as any))?.pageGroupKey ?? ((((BMRuntime7_orders_index as any).metadata) as any))?.groupKey, icon: ((((BMRuntime7_orders_index as any).metadata) as any))?.icon, order: ((((BMRuntime7_orders_index as any).metadata) as any))?.pageOrder ?? ((((BMRuntime7_orders_index as any).metadata) as any))?.order, priority: ((((BMRuntime7_orders_index as any).metadata) as any))?.pagePriority ?? ((((BMRuntime7_orders_index as any).metadata) as any))?.priority, navHidden: ((((BMRuntime7_orders_index as any).metadata) as any))?.navHidden, visible: ((((BMRuntime7_orders_index as any).metadata) as any))?.visible, enabled: ((((BMRuntime7_orders_index as any).metadata) as any))?.enabled, breadcrumb: ((((BMRuntime7_orders_index as any).metadata) as any))?.breadcrumb, pageContext: ((((BMRuntime7_orders_index as any).metadata) as any))?.pageContext, placement: ((((BMRuntime7_orders_index as any).metadata) as any))?.placement, Component: async (props: any) => { const mod = await import("@open-mercato/core/modules/orders/backend/page"); const Component = (mod.default ?? mod) as any; return createElement(Component, props) } }],
            apis: [{ path: "/orders/orders", metadata: undefined, handlers: { GET: async (req: Request, ctx?: any) => { const mod = await import("@open-mercato/core/modules/orders/api/orders/route"); return (mod as any).GET(req, ctx) } } }],
            
            
            
            
            customFieldSets: [],
            
            
            
            
            
            
          }
      ]
      export const modulesInfo = modules.map(m => ({ id: m.id, ...(m.info || {}) }))
      export default modules
    `))
    expect(readGenerated(tmpDir, 'frontend-routes.generated.ts')).toBe(dedent(`
      // AUTO-GENERATED by mercato generate registry
      import type { FrontendRouteManifestEntry } from '@open-mercato/shared/modules/registry'

      export const frontendRoutes: FrontendRouteManifestEntry[] = [
        { moduleId: "orders", pattern: "/", requireAuth: ((undefined as any))?.requireAuth, requireRoles: ((undefined as any))?.requireRoles, requireFeatures: ((undefined as any))?.requireFeatures, requireCustomerAuth: ((undefined as any))?.requireCustomerAuth, requireCustomerFeatures: ((undefined as any))?.requireCustomerFeatures, nav: ((undefined as any))?.nav, title: ((undefined as any))?.pageTitle ?? ((undefined as any))?.title, titleKey: ((undefined as any))?.pageTitleKey ?? ((undefined as any))?.titleKey, group: ((undefined as any))?.pageGroup ?? ((undefined as any))?.group, groupKey: ((undefined as any))?.pageGroupKey ?? ((undefined as any))?.groupKey, icon: ((undefined as any))?.icon, order: ((undefined as any))?.pageOrder ?? ((undefined as any))?.order, priority: ((undefined as any))?.pagePriority ?? ((undefined as any))?.priority, navHidden: ((undefined as any))?.navHidden, visible: ((undefined as any))?.visible, enabled: ((undefined as any))?.enabled, breadcrumb: ((undefined as any))?.breadcrumb, pageContext: ((undefined as any))?.pageContext, placement: ((undefined as any))?.placement, load: async () => { const mod = await import("@open-mercato/core/modules/orders/frontend/page"); return (mod.default ?? mod) as any } }
      ]

      export default frontendRoutes
    `))
    expect(readGenerated(tmpDir, 'backend-routes.generated.ts')).toBe(dedent(`
      // AUTO-GENERATED by mercato generate registry
      import type { BackendRouteManifestEntry } from '@open-mercato/shared/modules/registry'

      export const backendRoutes: BackendRouteManifestEntry[] = [
        { moduleId: "orders", pattern: "/backend/orders", requireAuth: ((undefined as any))?.requireAuth, requireRoles: ((undefined as any))?.requireRoles, requireFeatures: ((undefined as any))?.requireFeatures, requireCustomerAuth: ((undefined as any))?.requireCustomerAuth, requireCustomerFeatures: ((undefined as any))?.requireCustomerFeatures, nav: ((undefined as any))?.nav, title: ((undefined as any))?.pageTitle ?? ((undefined as any))?.title, titleKey: ((undefined as any))?.pageTitleKey ?? ((undefined as any))?.titleKey, group: ((undefined as any))?.pageGroup ?? ((undefined as any))?.group, groupKey: ((undefined as any))?.pageGroupKey ?? ((undefined as any))?.groupKey, icon: ((undefined as any))?.icon, order: ((undefined as any))?.pageOrder ?? ((undefined as any))?.order, priority: ((undefined as any))?.pagePriority ?? ((undefined as any))?.priority, navHidden: ((undefined as any))?.navHidden, visible: ((undefined as any))?.visible, enabled: ((undefined as any))?.enabled, breadcrumb: ((undefined as any))?.breadcrumb, pageContext: ((undefined as any))?.pageContext, placement: ((undefined as any))?.placement, load: async () => { const mod = await import("@open-mercato/core/modules/orders/backend/page"); return (mod.default ?? mod) as any } }
      ]

      export default backendRoutes
    `))
    expect(readGenerated(tmpDir, 'api-routes.generated.ts')).toBe(dedent(`
      // AUTO-GENERATED by mercato generate registry
      import type { ApiRouteManifestEntry } from '@open-mercato/shared/modules/registry'

      export const apiRoutes: ApiRouteManifestEntry[] = [
        { moduleId: "orders", kind: "route-file", path: "/orders/orders", methods: ["GET"], load: async () => import("@open-mercato/core/modules/orders/api/orders/route") }
      ]

      export default apiRoutes
    `))
  })

  it('generates valid output with a single module that has no files', async () => {
    const enabled: ModuleEntry[] = [
      { id: 'empty_mod', from: '@open-mercato/core' },
    ]
    const resolver = createMockResolver(tmpDir, enabled)
    const result = await generateModuleRegistry({ resolver, quiet: true })

    expect(result.errors).toEqual([])
    const output = readGenerated(tmpDir, 'modules.generated.ts')
    expect(output).toContain('id: "empty_mod"')
  })

  it('handles module with only subscribers — no pages or APIs', async () => {
    scaffoldModule(tmpDir, 'notifications_only', 'pkg', [
      'subscribers/on-order.ts',
      'subscribers/on-payment.ts',
    ])
    const enabled: ModuleEntry[] = [
      { id: 'notifications_only', from: '@open-mercato/core' },
    ]
    const resolver = createMockResolver(tmpDir, enabled)
    const result = await generateModuleRegistry({ resolver, quiet: true })

    expect(result.errors).toEqual([])
    const output = readGenerated(tmpDir, 'modules.generated.ts')!
    expect(output).toContain('id: "notifications_only"')
    expect(output).toContain('subscribers:')
    expect(output).not.toContain('frontendRoutes:')
    expect(output).not.toContain('backendRoutes:')
    expect(output).not.toContain('apis:')
  })

  it('extracts subscriber metadata from source when runtime import fails', async () => {
    touchFile(
      path.join(tmpDir, 'packages', 'core', 'src', 'modules', 'subscriber_meta', 'lib', 'helper.ts'),
      'export const helper = true\n',
    )
    touchFile(
      path.join(tmpDir, 'packages', 'core', 'src', 'modules', 'subscriber_meta', 'subscribers', 'on-event.ts'),
      "import { helper } from '../lib/helper'\nexport const metadata = { event: 'subscriber.meta.created', persistent: false }\nexport default async function handler() { return helper }\n",
    )

    const enabled: ModuleEntry[] = [
      { id: 'subscriber_meta', from: '@open-mercato/core' },
    ]
    const resolver = createMockResolver(tmpDir, enabled)
    const result = await generateModuleRegistry({ resolver, quiet: true })

    expect(result.errors).toEqual([])
    const output = readGenerated(tmpDir, 'modules.generated.ts')!
    expect(output).toContain('subscriber.meta.created')
    expect(output).toContain('subscriber_meta:on-event')
  })

  it('extracts worker metadata from imported queue constants when runtime import fails', async () => {
    touchFile(
      path.join(tmpDir, 'packages', 'core', 'src', 'modules', 'worker_meta', 'lib', 'queue.ts'),
      "export const IMPORTED_QUEUE = 'worker.meta.queue'\n",
    )
    touchFile(
      path.join(tmpDir, 'packages', 'core', 'src', 'modules', 'worker_meta', 'workers', 'process-job.ts'),
      [
        "import { IMPORTED_QUEUE } from '../lib/queue'",
        "import { helper } from '../lib/helper'",
        "export const metadata = { queue: IMPORTED_QUEUE, id: 'worker_meta:process-job', concurrency: 4 }",
        'export default async function handle() { return helper }',
        '',
      ].join('\n'),
    )
    touchFile(
      path.join(tmpDir, 'packages', 'core', 'src', 'modules', 'worker_meta', 'lib', 'helper.ts'),
      'export const helper = true\n',
    )

    const resolver = createMockResolver(tmpDir, [
      { id: 'worker_meta', from: '@open-mercato/core' },
    ])

    const result = await generateModuleRegistry({ resolver, quiet: true })

    expect(result.errors).toEqual([])
    const output = readGenerated(tmpDir, 'modules.generated.ts')!
    expect(output).toContain('queue: "worker.meta.queue"')
    expect(output).toContain('id: "worker_meta:process-job"')
    expect(output).toContain('concurrency: 4')
  })

  it('extracts subscriber metadata from imported event objects when runtime import fails', async () => {
    touchFile(
      path.join(tmpDir, 'packages', 'core', 'src', 'modules', 'subscriber_event_meta', 'lib', 'events.ts'),
      [
        'export const SUBSCRIBER_EVENTS = {',
        "  CREATED: 'subscriber.event.created',",
        "} as const",
        '',
      ].join('\n'),
    )
    touchFile(
      path.join(tmpDir, 'packages', 'core', 'src', 'modules', 'subscriber_event_meta', 'lib', 'helper.ts'),
      'export const helper = true\n',
    )
    touchFile(
      path.join(tmpDir, 'packages', 'core', 'src', 'modules', 'subscriber_event_meta', 'subscribers', 'on-created.ts'),
      [
        "import { helper } from '../lib/helper'",
        "import { SUBSCRIBER_EVENTS } from '../lib/events'",
        "export const metadata = { event: SUBSCRIBER_EVENTS.CREATED, persistent: true, id: 'subscriber_event_meta:on-created' }",
        'export default async function handle() { return helper }',
        '',
      ].join('\n'),
    )

    const resolver = createMockResolver(tmpDir, [
      { id: 'subscriber_event_meta', from: '@open-mercato/core' },
    ])

    const result = await generateModuleRegistry({ resolver, quiet: true })

    expect(result.errors).toEqual([])
    const output = readGenerated(tmpDir, 'modules.generated.ts')!
    expect(output).toContain('subscriber.event.created')
    expect(output).toContain('subscriber_event_meta:on-created')
  })

  it('keeps backend route metadata runtime-backed when icons are non-serializable', async () => {
    touchFile(
      path.join(tmpDir, 'packages', 'core', 'src', 'modules', 'iconic', 'backend', 'dashboard', 'page.tsx'),
      'export default function Page() { return null }\n',
    )
    touchFile(
      path.join(tmpDir, 'packages', 'core', 'src', 'modules', 'iconic', 'backend', 'dashboard', 'page.meta.ts'),
      "import React from 'react'\nconst icon = React.createElement('svg', null)\nexport const metadata = { requireAuth: true, pageTitle: 'Dashboard', icon }\n",
    )

    const enabled: ModuleEntry[] = [
      { id: 'iconic', from: '@open-mercato/core' },
    ]
    const resolver = createMockResolver(tmpDir, enabled)
    const result = await generateModuleRegistry({ resolver, quiet: true })

    expect(result.errors).toEqual([])
    const output = readGenerated(tmpDir, 'backend-routes.generated.ts')!
    expect(output).toMatch(/import \* as .* from "@open-mercato\/core\/modules\/iconic\/backend\/dashboard\/page\.meta"/)
    expect(output).not.toContain('"pageTitle":"Dashboard"')
    expect(output).toContain('pattern: "/backend/dashboard"')
  })

  it('handles module with only widgets — no pages or subscribers', async () => {
    scaffoldModule(tmpDir, 'widgets_only', 'pkg', [
      'widgets/dashboard/stats/widget.tsx',
      'widgets/injection/sidebar/widget.tsx',
    ])
    const enabled: ModuleEntry[] = [
      { id: 'widgets_only', from: '@open-mercato/core' },
    ]
    const resolver = createMockResolver(tmpDir, enabled)
    const result = await generateModuleRegistry({ resolver, quiet: true })

    expect(result.errors).toEqual([])
    const output = readGenerated(tmpDir, 'modules.generated.ts')!
    expect(output).toContain('id: "widgets_only"')
    expect(output).toContain('dashboardWidgets:')
    expect(output).not.toContain('subscribers:')

    const widgetsOutput = readGenerated(tmpDir, 'dashboard-widgets.generated.ts')!
    expect(widgetsOutput).toContain('widgets_only')

    const injectionOutput = readGenerated(tmpDir, 'injection-widgets.generated.ts')!
    expect(injectionOutput).toContain('widgets_only')
  })

  it('handles module with only convention files — no walk-based scans', async () => {
    scaffoldModule(tmpDir, 'config_mod', 'pkg', [
      'acl.ts',
      'setup.ts',
      'ce.ts',
      'translations.ts',
      'data/extensions.ts',
      'data/fields.ts',
    ])
    const enabled: ModuleEntry[] = [
      { id: 'config_mod', from: '@open-mercato/core' },
    ]
    const resolver = createMockResolver(tmpDir, enabled)
    const result = await generateModuleRegistry({ resolver, quiet: true })

    expect(result.errors).toEqual([])
    const output = readGenerated(tmpDir, 'modules.generated.ts')!
    expect(output).toContain('id: "config_mod"')
    expect(output).toContain('features:')
    expect(output).toContain('entityExtensions:')
    expect(output).toContain('customFieldSets:')
    expect(output).toContain('setup:')

    const transFields = readGenerated(tmpDir, 'translations-fields.generated.ts')!
    expect(transFields).toContain('config_mod')
  })

  it('keeps all HTTP methods for route.ts files that re-export crud handlers', async () => {
    scaffoldModule(tmpDir, 'customers', 'pkg', ['api/people/route.ts'])
    touchFile(
      path.join(tmpDir, 'packages', 'core', 'src', 'modules', 'customers', 'api', 'people', 'route.ts'),
      `const crud = {
  GET() { return null },
  POST() { return null },
  PUT() { return null },
  DELETE() { return null },
}

const { POST, PUT, DELETE } = crud

export function GET() {
  return null
}

export { POST, PUT, DELETE }
`
    )

    const resolver = createMockResolver(tmpDir, [{ id: 'customers', from: '@open-mercato/core' }])
    const result = await generateModuleRegistry({ resolver, quiet: true })

    expect(result.errors).toEqual([])
    const apiRoutes = readGenerated(tmpDir, 'api-routes.generated.ts')!
    expect(apiRoutes).toContain('path: "/customers/people"')
    expect(apiRoutes).toContain('methods: ["GET", "POST", "PUT", "DELETE"]')
  })

  it('keeps all HTTP methods for route.ts files that destructure-export crud handlers', async () => {
    scaffoldModule(tmpDir, 'example', 'pkg', ['api/todos/route.ts'])
    touchFile(
      path.join(tmpDir, 'packages', 'core', 'src', 'modules', 'example', 'api', 'todos', 'route.ts'),
      `const crud = {
  metadata: {},
  GET() { return null },
  POST() { return null },
  PUT() { return null },
  DELETE() { return null },
}

export const { metadata, GET, POST, PUT, DELETE } = crud
`
    )

    const resolver = createMockResolver(tmpDir, [{ id: 'example', from: '@open-mercato/core' }])
    const result = await generateModuleRegistry({ resolver, quiet: true })

    expect(result.errors).toEqual([])
    const apiRoutes = readGenerated(tmpDir, 'api-routes.generated.ts')!
    expect(apiRoutes).toContain('path: "/example/todos"')
    expect(apiRoutes).toContain('methods: ["GET", "POST", "PUT", "DELETE"]')
  })

  it('uses metadata.path in api route manifests when source import fails during generation', async () => {
    scaffoldModule(tmpDir, 'shipping_carriers', 'pkg', ['api/providers/route.ts', 'lib/registry.ts'])
    touchFile(
      path.join(tmpDir, 'packages', 'core', 'src', 'modules', 'shipping_carriers', 'lib', 'registry.ts'),
      'export const registry = true\n'
    )
    touchFile(
      path.join(tmpDir, 'packages', 'core', 'src', 'modules', 'shipping_carriers', 'api', 'providers', 'route.ts'),
      `import { registry } from '../../lib/registry'

export const metadata = {
  path: '/shipping-carriers/providers',
  GET: { requireAuth: true },
}

export function GET() {
  return registry
}
`
    )

    const resolver = createMockResolver(tmpDir, [{ id: 'shipping_carriers', from: '@open-mercato/core' }])
    const result = await generateModuleRegistry({ resolver, quiet: true })

    expect(result.errors).toEqual([])
    const apiRoutes = readGenerated(tmpDir, 'api-routes.generated.ts')!
    expect(apiRoutes).toContain('path: "/shipping-carriers/providers"')
    expect(apiRoutes).not.toContain('path: "/shipping_carriers/providers"')
  })

  it('generates correct output when full module is later disabled', async () => {
    // First: generate with two modules
    scaffoldModule(tmpDir, 'mod_a', 'pkg', [
      'backend/page.tsx',
      'subscribers/on-created.ts',
      'acl.ts',
    ])
    scaffoldModule(tmpDir, 'mod_b', 'pkg', [
      'backend/page.tsx',
      'widgets/dashboard/chart/widget.tsx',
      'acl.ts',
    ])

    const allEnabled: ModuleEntry[] = [
      { id: 'mod_a', from: '@open-mercato/core' },
      { id: 'mod_b', from: '@open-mercato/core' },
    ]
    const resolverAll = createMockResolver(tmpDir, allEnabled)
    const resultAll = await generateModuleRegistry({ resolver: resolverAll, quiet: true })
    expect(resultAll.errors).toEqual([])

    const outputAll = readGenerated(tmpDir, 'modules.generated.ts')!
    expect(outputAll).toContain('id: "mod_a"')
    expect(outputAll).toContain('id: "mod_b"')

    // Second: regenerate with mod_b disabled (only mod_a)
    const subsetEnabled: ModuleEntry[] = [
      { id: 'mod_a', from: '@open-mercato/core' },
    ]
    const resolverSubset = createMockResolver(tmpDir, subsetEnabled)
    const resultSubset = await generateModuleRegistry({
      resolver: resolverSubset,
      quiet: true,
    })
    expect(resultSubset.errors).toEqual([])

    const outputSubset = readGenerated(tmpDir, 'modules.generated.ts')!
    expect(outputSubset).toContain('id: "mod_a"')
    expect(outputSubset).not.toContain('id: "mod_b"')

    // Widgets file should no longer reference mod_b
    const widgetsSubset = readGenerated(tmpDir, 'dashboard-widgets.generated.ts')!
    expect(widgetsSubset).not.toContain('mod_b')
  })

  it('handles @app module that only exists in app dir (no pkg counterpart)', async () => {
    scaffoldModule(tmpDir, 'custom_app', 'app', [
      'backend/page.tsx',
      'subscribers/my-handler.ts',
      'widgets/dashboard/my-widget/widget.tsx',
      'acl.ts',
    ])
    touchFile(
      path.join(tmpDir, 'app', 'src', 'modules', 'custom_app', 'backend', 'page.tsx'),
      'export default function CustomAppPage() { return null }\n',
    )
    const enabled: ModuleEntry[] = [{ id: 'custom_app', from: '@app' }]
    const resolver = createMockResolver(tmpDir, enabled)
    const result = await generateModuleRegistry({ resolver, quiet: true })

    expect(result.errors).toEqual([])
    const output = readGenerated(tmpDir, 'modules.generated.ts')!
    expect(output).toContain('id: "custom_app"')
    expect(output).toContain('backendRoutes:')
    expect(output).toContain('subscribers:')
    expect(output).toContain('dashboardWidgets:')
    expect(output).toContain('features:')
  })

  it('escapes generated module specifiers for lazy imports', async () => {
    touchFile(
      path.join(tmpDir, 'packages', 'core', 'src', 'modules', 'safe_mod', 'subscribers', `o'hare.ts`),
      `export const metadata = { event: 'orders.created' }\nexport default async function handler() {}\n`
    )
    touchFile(
      path.join(tmpDir, 'packages', 'core', 'src', 'modules', 'safe_mod', 'workers', `queue'oops.ts`),
      `export const metadata = { queue: 'sync.jobs', concurrency: 2 }\nexport default async function handler() {}\n`
    )
    touchFile(
      path.join(tmpDir, 'packages', 'core', 'src', 'modules', 'safe_mod', 'api', 'get', `quoted'route.ts`),
      `export const metadata = { path: '/safe_mod/quoted-route' }\nexport async function GET() { return new Response('ok') }\n`
    )

    const enabled: ModuleEntry[] = [
      { id: 'safe_mod', from: '@open-mercato/core' },
    ]
    const resolver = createMockResolver(tmpDir, enabled)
    const result = await generateModuleRegistry({ resolver, quiet: true })

    expect(result.errors).toEqual([])
    const output = readGenerated(tmpDir, 'modules.generated.ts')!
    expect(output).toContain(`createLazyModuleSubscriber(() => import("@open-mercato/core/modules/safe_mod/subscribers/o'hare")`)
    expect(output).toContain(`createLazyModuleWorker(() => import("@open-mercato/core/modules/safe_mod/workers/queue'oops")`)
    expect(output).toContain(`from "@open-mercato/core/modules/safe_mod/api/get/quoted'route"`)
    expect(output).not.toContain(`import('@open-mercato/core/modules/safe_mod/subscribers/o'hare')`)
    expect(output).not.toContain(`import('@open-mercato/core/modules/safe_mod/workers/queue'oops')`)
    expect(output).not.toContain(`?? '/safe_mod/quoted'route'`)
    expect(output).not.toContain(`path: '/safe_mod/quoted'route'`)
  })

  it('rejects unsafe generated module specifiers before emitting lazy imports', async () => {
    scaffoldModule(tmpDir, 'bad_spec', 'pkg', ['subscribers/on-event.ts'])
    touchFile(
      path.join(tmpDir, 'packages', 'core', 'src', 'modules', 'bad_spec', 'subscribers', 'on-event.ts'),
      `export const metadata = { event: 'orders.created' }\nexport default async function handler() {}\n`
    )

    const baseResolver = createMockResolver(tmpDir, [
      { id: 'bad_spec', from: '@open-mercato/core' },
    ])
    const resolver: PackageResolver = {
      ...baseResolver,
      getModuleImportBase: () => ({
        appBase: '@/modules/bad_spec',
        pkgBase: '@open-mercato/core/modules/bad_spec";console.log(1)//',
      }),
    }

    await expect(generateModuleRegistry({ resolver, quiet: true })).rejects.toThrow(
      'Unsafe generated module specifier'
    )
  })

  it('mixed subset: core module + app module, then remove core module', async () => {
    scaffoldModule(tmpDir, 'core_mod', 'pkg', [
      'backend/page.tsx',
      'search.ts',
    ])
    scaffoldModule(tmpDir, 'app_mod', 'app', [
      'backend/page.tsx',
      'widgets/dashboard/info/widget.tsx',
    ])

    const both: ModuleEntry[] = [
      { id: 'core_mod', from: '@open-mercato/core' },
      { id: 'app_mod', from: '@app' },
    ]
    const resolverBoth = createMockResolver(tmpDir, both)
    const resultBoth = await generateModuleRegistry({ resolver: resolverBoth, quiet: true })
    expect(resultBoth.errors).toEqual([])

    const outputBoth = readGenerated(tmpDir, 'modules.generated.ts')!
    expect(outputBoth).toContain('id: "core_mod"')
    expect(outputBoth).toContain('id: "app_mod"')

    const searchBoth = readGenerated(tmpDir, 'search.generated.ts')!
    expect(searchBoth).toContain('core_mod')

    // Now remove core_mod, only app_mod remains
    const appOnly: ModuleEntry[] = [{ id: 'app_mod', from: '@app' }]
    const resolverApp = createMockResolver(tmpDir, appOnly)
    const resultApp = await generateModuleRegistry({ resolver: resolverApp, quiet: true })
    expect(resultApp.errors).toEqual([])

    const outputApp = readGenerated(tmpDir, 'modules.generated.ts')!
    expect(outputApp).not.toContain('id: "core_mod"')
    expect(outputApp).toContain('id: "app_mod"')

    // Search should no longer reference core_mod
    const searchApp = readGenerated(tmpDir, 'search.generated.ts')!
    expect(searchApp).not.toContain('core_mod')
  })

  it('uses standalone source mirror i18n files when dist modules omit translation assets', async () => {
    touchFile(
      path.join(tmpDir, 'node_modules', 'pkg', 'src', 'modules', 'customers', 'i18n', 'en.json'),
      JSON.stringify({ customers: { people: { list: { title: 'People' } } } }),
    )
    touchFile(
      path.join(tmpDir, 'node_modules', 'pkg', 'src', 'modules', 'customers', 'translations.ts'),
      'export const translatableFields = {}\n',
    )
    touchFile(
      path.join(tmpDir, 'node_modules', 'pkg', 'dist', 'modules', 'customers', 'index.js'),
      'export const metadata = { id: "customers" }\n',
    )
    touchFile(
      path.join(tmpDir, 'node_modules', 'pkg', 'dist', 'modules', 'customers', 'translations.js'),
      'export const translatableFields = {}\n',
    )

    const resolver = createStandaloneMockResolver(tmpDir, [
      { id: 'customers', from: '@open-mercato/core' },
    ])
    const result = await generateModuleRegistry({ resolver, quiet: true })

    expect(result.errors).toEqual([])

    const output = fs.readFileSync(
      path.join(tmpDir, '.mercato', 'generated', 'modules.generated.ts'),
      'utf8',
    )

    expect(output).toContain('@open-mercato/core/modules/customers/i18n/en.json')
    expect(output).toContain(`'en':`)
  })
})

describe('generateModuleRegistryCli with module subsets', () => {
  it('generates valid output with zero modules enabled', async () => {
    const resolver = createMockResolver(tmpDir, [])
    const result = await generateModuleRegistryCli({ resolver, quiet: true })

    expect(result.errors).toEqual([])
    const output = readGenerated(tmpDir, 'modules.cli.generated.ts')
    expect(output).not.toBeNull()
    expect(output).toContain('export const modules: Module[] = [')
  })

  it('CLI output excludes pages and APIs even when module has them', async () => {
    scaffoldModule(tmpDir, 'full_mod', 'pkg', [
      'index.ts',
      'frontend/page.tsx',
      'backend/page.tsx',
      'api/route.ts',
      'subscribers/on-event.ts',
      'workers/process-job.ts',
      'widgets/dashboard/stats/widget.tsx',
      'acl.ts',
      'setup.ts',
    ])
    const enabled: ModuleEntry[] = [
      { id: 'full_mod', from: '@open-mercato/core' },
    ]
    const resolver = createMockResolver(tmpDir, enabled)
    const result = await generateModuleRegistryCli({ resolver, quiet: true })

    expect(result.errors).toEqual([])
    const output = readGenerated(tmpDir, 'modules.cli.generated.ts')!
    expect(output).toContain('id: "full_mod"')
    // CLI excludes these:
    expect(output).not.toContain('frontendRoutes:')
    expect(output).not.toContain('backendRoutes:')
    expect(output).not.toContain('apis:')
    // CLI includes these:
    expect(output).toContain('subscribers:')
    expect(output).toContain('features:')
    expect(output).toContain('setup:')
    expect(output).toContain('dashboardWidgets:')
  })

  it('includes app-owned workers in generated module metadata', async () => {
    scaffoldModule(tmpDir, 'app_worker_mod', 'app', [
      'index.ts',
      'workers/process-job.ts',
    ])
    touchFile(
      path.join(tmpDir, 'app', 'src', 'modules', 'app_worker_mod', 'workers', 'process-job.ts'),
      `
export const metadata = { queue: 'app-worker-queue', id: 'app-worker-mod:process-job', concurrency: 2 }
export default async function handle(): Promise<void> {}
      `.trim(),
    )

    const resolver = createMockResolver(tmpDir, [
      { id: 'app_worker_mod', from: '@app' },
    ])

    const result = await generateModuleRegistry({ resolver, quiet: true })

    expect(result.errors).toEqual([])
    const output = readGenerated(tmpDir, 'modules.generated.ts')!
    expect(output).toContain('id: "app_worker_mod"')
    expect(output).toContain('queue: "app-worker-queue"')
    expect(output).toContain('concurrency: 2')
    expect(output).toContain('createLazyModuleWorker(() => import("../../src/modules/app_worker_mod/workers/process-job")')
    expect(output).toContain("workers:")
  })

  it('handles disabling a module that was previously enabled', async () => {
    scaffoldModule(tmpDir, 'keep_mod', 'pkg', [
      'subscribers/handler.ts',
      'acl.ts',
    ])
    scaffoldModule(tmpDir, 'drop_mod', 'pkg', [
      'subscribers/handler.ts',
      'setup.ts',
    ])

    const all: ModuleEntry[] = [
      { id: 'keep_mod', from: '@open-mercato/core' },
      { id: 'drop_mod', from: '@open-mercato/core' },
    ]
    const resolverAll = createMockResolver(tmpDir, all)
    const resultAll = await generateModuleRegistryCli({ resolver: resolverAll, quiet: true })
    expect(resultAll.errors).toEqual([])
    const outputAll = readGenerated(tmpDir, 'modules.cli.generated.ts')!
    expect(outputAll).toContain('id: "keep_mod"')
    expect(outputAll).toContain('id: "drop_mod"')

    // Disable drop_mod
    const subset: ModuleEntry[] = [
      { id: 'keep_mod', from: '@open-mercato/core' },
    ]
    const resolverSubset = createMockResolver(tmpDir, subset)
    const resultSubset = await generateModuleRegistryCli({
      resolver: resolverSubset,
      quiet: true,
    })
    expect(resultSubset.errors).toEqual([])
    const outputSubset = readGenerated(tmpDir, 'modules.cli.generated.ts')!
    expect(outputSubset).toContain('id: "keep_mod"')
    expect(outputSubset).not.toContain('id: "drop_mod"')
  })

  it('discovers workers from standalone dist/modules output', async () => {
    touchFile(
      path.join(tmpDir, 'node_modules', 'pkg', 'dist', 'modules', 'data_sync', 'workers', 'sync-import.js'),
      "export const metadata = { queue: 'data-sync-import', concurrency: 5 }\nexport default async function handler() {}\n"
    )
    touchFile(
      path.join(tmpDir, 'node_modules', 'pkg', 'dist', 'modules', 'data_sync', 'workers', 'sync-export.js'),
      "export const metadata = { queue: 'data-sync-export', concurrency: 5 }\nexport default async function handler() {}\n"
    )
    touchFile(
      path.join(tmpDir, 'node_modules', 'pkg', 'dist', 'modules', 'integrations', 'workers', 'log-pruner.js'),
      "export const metadata = { queue: 'integration-log-pruner', concurrency: 1 }\nexport default async function handler() {}\n"
    )

    const resolver = createStandaloneMockResolver(tmpDir, [
      { id: 'data_sync', from: '@open-mercato/core' },
      { id: 'integrations', from: '@open-mercato/core' },
    ])
    const result = await generateModuleRegistryCli({ resolver, quiet: true })

    expect(result.errors).toEqual([])
    const outputPath = path.join(tmpDir, '.mercato', 'generated', 'modules.cli.generated.ts')
    const output = fs.readFileSync(outputPath, 'utf8')
    expect(output).toContain('queue: "data-sync-import"')
    expect(output).toContain('queue: "data-sync-export"')
    expect(output).toContain('queue: "integration-log-pruner"')
    expect(output).toContain('createLazyModuleWorker(() => import("@open-mercato/core/modules/data_sync/workers/sync-import")')
  })

  it('discovers CLI metadata and ACL from standalone dist/modules output', async () => {
    touchFile(
      path.join(tmpDir, 'node_modules', 'pkg', 'dist', 'modules', 'configs', 'index.js'),
      "exports.metadata = { name: 'Configs', requires: ['auth'] }\n"
    )
    touchFile(
      path.join(tmpDir, 'node_modules', 'pkg', 'dist', 'modules', 'configs', 'cli.js'),
      "module.exports = [{ command: 'restore-defaults', run: async () => {} }]\n"
    )
    touchFile(
      path.join(tmpDir, 'node_modules', 'pkg', 'dist', 'modules', 'configs', 'acl.js'),
      "exports.features = ['configs.manage']\n"
    )

    const enabled: ModuleEntry[] = [
      { id: 'configs', from: '@open-mercato/core' },
      { id: 'auth', from: '@open-mercato/core' },
    ]
    const resolver = createStandaloneMockResolver(tmpDir, enabled)
    const result = await generateModuleRegistryCli({ resolver, quiet: true })

    expect(result.errors).toEqual([])
    const outputPath = path.join(tmpDir, '.mercato', 'generated', 'modules.cli.generated.ts')
    const output = fs.readFileSync(outputPath, 'utf8')
    expect(output).toContain('import CLI_configs from "@open-mercato/core/modules/configs/cli"')
    expect(output).toContain('cli: CLI_configs')
    expect(output).toContain('features:')
    expect(output).toContain('id: "configs"')
  })

  it('preserves standalone CLI convention files when discovery uses a src mirror', async () => {
    touchFile(
      path.join(tmpDir, 'node_modules', 'pkg', 'src', 'modules', 'configs', 'index.ts'),
      "export const metadata = { name: 'Configs', requires: ['auth'] }\n",
    )
    touchFile(
      path.join(tmpDir, 'node_modules', 'pkg', 'src', 'modules', 'configs', 'cli.ts'),
      "export default [{ command: 'restore-defaults', run: async () => {} }]\n",
    )
    touchFile(
      path.join(tmpDir, 'node_modules', 'pkg', 'src', 'modules', 'configs', 'acl.ts'),
      "export const features = ['configs.manage']\n",
    )
    touchFile(
      path.join(tmpDir, 'node_modules', 'pkg', 'dist', 'modules', 'configs', 'index.js'),
      "exports.metadata = { name: 'Configs', requires: ['auth'] }\n",
    )
    touchFile(
      path.join(tmpDir, 'node_modules', 'pkg', 'dist', 'modules', 'configs', 'cli.js'),
      "module.exports = [{ command: 'restore-defaults', run: async () => {} }]\n",
    )
    touchFile(
      path.join(tmpDir, 'node_modules', 'pkg', 'dist', 'modules', 'configs', 'acl.js'),
      "exports.features = ['configs.manage']\n",
    )

    const enabled: ModuleEntry[] = [
      { id: 'configs', from: '@open-mercato/core' },
      { id: 'auth', from: '@open-mercato/core' },
    ]
    const resolver = createStandaloneMockResolver(tmpDir, enabled)
    const result = await generateModuleRegistryCli({ resolver, quiet: true })

    expect(result.errors).toEqual([])
    const outputPath = path.join(tmpDir, '.mercato', 'generated', 'modules.cli.generated.ts')
    const output = fs.readFileSync(outputPath, 'utf8')
    expect(output).toContain('import CLI_configs from "@open-mercato/core/modules/configs/cli"')
    expect(output).toContain('cli: CLI_configs')
    expect(output).toContain('features:')
    expect(output).toContain('id: "configs"')
  })

  it('preserves standalone worker and subscriber metadata when discovery uses a src mirror', async () => {
    touchFile(
      path.join(tmpDir, 'node_modules', 'pkg', 'package.json'),
      JSON.stringify({ name: 'pkg', type: 'module' }),
    )
    touchFile(
      path.join(tmpDir, 'node_modules', 'pkg', 'src', 'modules', 'query_index', 'subscribers', 'reindex.ts'),
      "export const metadata = { event: 'query_index.reindex', persistent: true }\nexport default async function handler() {}\n",
    )
    touchFile(
      path.join(tmpDir, 'node_modules', 'pkg', 'dist', 'modules', 'query_index', 'subscribers', 'reindex.js'),
      "export const metadata = { event: 'query_index.reindex', persistent: true }\nexport default async function handler() {}\n",
    )
    touchFile(
      path.join(tmpDir, 'node_modules', 'pkg', 'src', 'modules', 'events', 'workers', 'events.worker.ts'),
      "export const metadata = { queue: 'events', concurrency: 1 }\nexport default async function handler() {}\n",
    )
    touchFile(
      path.join(tmpDir, 'node_modules', 'pkg', 'dist', 'modules', 'events', 'workers', 'events.worker.js'),
      "export const metadata = { queue: 'events', concurrency: 1 }\nexport default async function handler() {}\n",
    )

    const resolver = createStandaloneMockResolver(tmpDir, [
      { id: 'query_index', from: '@open-mercato/core' },
      { id: 'events', from: '@open-mercato/events' },
    ])
    const result = await generateModuleRegistryCli({ resolver, quiet: true })

    expect(result.errors).toEqual([])
    const outputPath = path.join(tmpDir, '.mercato', 'generated', 'modules.cli.generated.ts')
    const output = fs.readFileSync(outputPath, 'utf8')
    expect(output).toContain('event: "query_index.reindex"')
    expect(output).toContain('persistent: true')
    expect(output).toContain('queue: "events"')
    expect(output).toContain('concurrency: 1')
    expect(output).toContain('createLazyModuleWorker(() => import("@open-mercato/core/modules/events/workers/events.worker")')
  })

  it('casts standalone vector config to the module vector type in CLI output', async () => {
    touchFile(
      path.join(tmpDir, 'node_modules', 'pkg', 'dist', 'modules', 'search', 'vector.js'),
      "export const vectorConfig = { entities: [] }\n",
    )

    const resolver = createStandaloneMockResolver(tmpDir, [
      { id: 'search', from: '@open-mercato/core' },
    ])
    const result = await generateModuleRegistryCli({ resolver, quiet: true })

    expect(result.errors).toEqual([])
    const outputPath = path.join(tmpDir, '.mercato', 'generated', 'modules.cli.generated.ts')
    const output = fs.readFileSync(outputPath, 'utf8')
    expect(output).toContain('vector:')
    expect(output).toContain("as Module['vector']")
  })

  it('refreshes standalone worker metadata after the source file changes in the same process', async () => {
    touchFile(
      path.join(tmpDir, 'node_modules', 'pkg', 'package.json'),
      JSON.stringify({ name: 'pkg', type: 'module' }),
    )
    const workerPath = path.join(
      tmpDir,
      'node_modules',
      'pkg',
      'dist',
      'modules',
      'events',
      'workers',
      'events.worker.js',
    )
    touchFile(
      workerPath,
      "export const metadata = { queue: 'events', concurrency: 1 }\nexport default async function handler() {}\n",
    )

    const resolver = createStandaloneMockResolver(tmpDir, [
      { id: 'events', from: '@open-mercato/events' },
    ])

    let result = await generateModuleRegistryCli({ resolver, quiet: true })
    expect(result.errors).toEqual([])

    const outputPath = path.join(tmpDir, '.mercato', 'generated', 'modules.cli.generated.ts')
    let output = fs.readFileSync(outputPath, 'utf8')
    expect(output).toContain('queue: "events"')
    expect(output).toContain('concurrency: 1')

    touchFile(
      workerPath,
      "export const metadata = { queue: 'events', concurrency: 4 }\nexport default async function handler() {}\n",
    )

    result = await generateModuleRegistryCli({ resolver, quiet: true })
    expect(result.errors).toEqual([])

    output = fs.readFileSync(outputPath, 'utf8')
    expect(output).toContain('queue: "events"')
    expect(output).toContain('concurrency: 4')
    expect(output).not.toContain('concurrency: 1')
  })

  it('does not treat standalone page.meta files as page components', async () => {
    touchFile(
      path.join(tmpDir, 'node_modules', 'pkg', 'dist', 'modules', 'iconic', 'backend', 'dashboard', 'page.js'),
      'export default function Page() { return null }\n',
    )
    touchFile(
      path.join(tmpDir, 'node_modules', 'pkg', 'dist', 'modules', 'iconic', 'backend', 'dashboard', 'page.meta.js'),
      "export const metadata = { requireAuth: true, pageTitle: 'Dashboard' }\n",
    )

    const resolver = createStandaloneMockResolver(tmpDir, [
      { id: 'iconic', from: '@open-mercato/core' },
    ])
    const result = await generateModuleRegistry({ resolver, quiet: true })

    expect(result.errors).toEqual([])

    const modulesOutputPath = path.join(tmpDir, '.mercato', 'generated', 'modules.generated.ts')
    const modulesOutput = fs.readFileSync(modulesOutputPath, 'utf8')
    expect(modulesOutput).toContain(
      'import * as BM',
    )
    expect(modulesOutput).not.toMatch(
      /import B\d+_[^,\n]*, \* as BM\d+_[^,\n]* from "@open-mercato\/core\/modules\/iconic\/backend\/dashboard\/page\.meta"/,
    )

    const routesOutputPath = path.join(tmpDir, '.mercato', 'generated', 'backend-routes.generated.ts')
    const routesOutput = fs.readFileSync(routesOutputPath, 'utf8')
    expect(routesOutput).toContain('@open-mercato/core/modules/iconic/backend/dashboard/page')
    expect(routesOutput).not.toContain('@open-mercato/core/modules/iconic/backend/dashboard/page.meta')
    expect(routesOutput).not.toMatch(
      /import B\d+_[^,\n]* from "@open-mercato\/core\/modules\/iconic\/backend\/dashboard\/page\.meta"/,
    )
  })

  it('ignores standalone helper files without default exports when scanning direct frontend/backend routes', async () => {
    touchFile(
      path.join(tmpDir, 'node_modules', 'pkg', 'dist', 'modules', 'auth', 'frontend', 'login.js'),
      'export default function LoginPage() { return null }\n',
    )
    touchFile(
      path.join(tmpDir, 'node_modules', 'pkg', 'dist', 'modules', 'auth', 'frontend', 'login-injection.js'),
      'export const loginInjectionContract = true\n',
    )
    touchFile(
      path.join(tmpDir, 'node_modules', 'pkg', 'dist', 'modules', 'auth', 'backend', 'users', 'list.js'),
      'export default function UsersListPage() { return null }\n',
    )
    touchFile(
      path.join(tmpDir, 'node_modules', 'pkg', 'dist', 'modules', 'auth', 'backend', 'users', 'roleOptions.js'),
      'export async function fetchRoleOptions() { return [] }\n',
    )

    const resolver = createStandaloneMockResolver(tmpDir, [
      { id: 'auth', from: '@open-mercato/core' },
    ])
    const result = await generateModuleRegistry({ resolver, quiet: true })

    expect(result.errors).toEqual([])

    const modulesOutputPath = path.join(tmpDir, '.mercato', 'generated', 'modules.generated.ts')
    const modulesOutput = fs.readFileSync(modulesOutputPath, 'utf8')
    expect(modulesOutput).toContain('@open-mercato/core/modules/auth/frontend/login')
    expect(modulesOutput).toContain('@open-mercato/core/modules/auth/backend/users/list')
    expect(modulesOutput).not.toContain('@open-mercato/core/modules/auth/frontend/login-injection')
    expect(modulesOutput).not.toContain('@open-mercato/core/modules/auth/backend/users/roleOptions')

    const frontendRoutesOutputPath = path.join(tmpDir, '.mercato', 'generated', 'frontend-routes.generated.ts')
    const frontendRoutesOutput = fs.readFileSync(frontendRoutesOutputPath, 'utf8')
    expect(frontendRoutesOutput).toContain('/login')
    expect(frontendRoutesOutput).not.toContain('login-injection')

    const backendRoutesOutputPath = path.join(tmpDir, '.mercato', 'generated', 'backend-routes.generated.ts')
    const backendRoutesOutput = fs.readFileSync(backendRoutesOutputPath, 'utf8')
    expect(backendRoutesOutput).toContain('/backend/auth/users/list')
    expect(backendRoutesOutput).not.toContain('roleOptions')
  })

  it('prefers standalone src module mirrors over dist-only legacy api artifacts', async () => {
    touchFile(
      path.join(tmpDir, 'node_modules', 'pkg', 'src', 'modules', 'payment_gateways', 'api', 'status', 'route.ts'),
      'export async function GET() { return new Response("ok") }\n',
    )
    touchFile(
      path.join(tmpDir, 'node_modules', 'pkg', 'dist', 'modules', 'payment_gateways', 'api', 'status', 'route.js'),
      'export async function GET() { return new Response("ok") }\n',
    )
    touchFile(
      path.join(tmpDir, 'node_modules', 'pkg', 'dist', 'modules', 'payment_gateways', 'api', 'get', 'payment-gateways', 'status.js'),
      'export async function GET() { return new Response("legacy") }\n',
    )

    const resolver = createStandaloneMockResolver(tmpDir, [
      { id: 'payment_gateways', from: '@open-mercato/core' },
    ])
    const result = await generateModuleRegistry({ resolver, quiet: true })

    expect(result.errors).toEqual([])

    const apiRoutesOutputPath = path.join(tmpDir, '.mercato', 'generated', 'api-routes.generated.ts')
    const apiRoutesOutput = fs.readFileSync(apiRoutesOutputPath, 'utf8')
    expect(apiRoutesOutput).toContain('@open-mercato/core/modules/payment_gateways/api/status/route')
    expect(apiRoutesOutput).not.toContain('@open-mercato/core/modules/payment_gateways/api/get/payment-gateways/status')
    expect(apiRoutesOutput).not.toContain('/payment_gateways/payment-gateways/status')
  })

  it('preserves metadata.path from compiled standalone route files that export metadata via export lists', async () => {
    touchFile(
      path.join(tmpDir, 'node_modules', 'pkg', 'dist', 'modules', 'shipping_carriers', 'api', 'providers', 'route.js'),
      [
        'import { NextResponse } from "next/server";',
        'const metadata = {',
        '  path: "/shipping-carriers/providers",',
        '  GET: { requireAuth: true },',
        '};',
        'async function GET() {',
        '  return NextResponse.json({ providers: [] });',
        '}',
        'export { GET, metadata };',
        '',
      ].join('\n'),
    )

    const resolver = createStandaloneMockResolver(tmpDir, [
      { id: 'shipping_carriers', from: '@open-mercato/core' },
    ])
    const result = await generateModuleRegistry({ resolver, quiet: true })

    expect(result.errors).toEqual([])

    const apiRoutesOutputPath = path.join(tmpDir, '.mercato', 'generated', 'api-routes.generated.ts')
    const apiRoutesOutput = fs.readFileSync(apiRoutesOutputPath, 'utf8')
    expect(apiRoutesOutput).toContain('path: "/shipping-carriers/providers"')
    expect(apiRoutesOutput).not.toContain('path: "/shipping_carriers/providers"')
  })

  it('keeps package legacy method handlers while letting app files override matching paths', async () => {
    touchFile(
      path.join(tmpDir, 'packages', 'core', 'src', 'modules', 'legacy_api', 'api', 'get', 'status.ts'),
      'export async function GET() { return new Response("package-status") }\n',
    )
    touchFile(
      path.join(tmpDir, 'packages', 'core', 'src', 'modules', 'legacy_api', 'api', 'get', 'details.ts'),
      'export async function GET() { return new Response("package-details") }\n',
    )
    touchFile(
      path.join(tmpDir, 'app', 'src', 'modules', 'legacy_api', 'api', 'get', 'status.ts'),
      'export async function GET() { return new Response("app-status") }\n',
    )

    const resolver = createMockResolver(tmpDir, [
      { id: 'legacy_api', from: '@open-mercato/core' },
    ])
    const result = await generateModuleRegistry({ resolver, quiet: true })

    expect(result.errors).toEqual([])

    const apiRoutesOutput = readGenerated(tmpDir, 'api-routes.generated.ts')!
    expect(apiRoutesOutput).toContain('@/modules/legacy_api/api/get/status')
    expect(apiRoutesOutput).not.toContain('@open-mercato/core/modules/legacy_api/api/get/status')
    expect(apiRoutesOutput).toContain('@open-mercato/core/modules/legacy_api/api/get/details')
    expect(apiRoutesOutput).toContain('path: "/legacy_api/details"')
    expect(apiRoutesOutput).toContain('path: "/legacy_api/status"')
  })
})

describe('generateModuleRegistryApp with module subsets', () => {
  it('generates valid output with zero modules enabled', async () => {
    const resolver = createMockResolver(tmpDir, [])
    const result = await generateModuleRegistryApp({ resolver, quiet: true })

    expect(result.errors).toEqual([])
    const output = readGenerated(tmpDir, 'modules.app.generated.ts')
    expect(output).not.toBeNull()
    expect(output).toContain('export const modules: Module[] = [')
  })

  it('app output excludes CLI commands and keeps lazy workers/subscribers', async () => {
    scaffoldModule(tmpDir, 'runtime_mod', 'pkg', [
      'index.ts',
      'cli.ts',
      'subscribers/on-event.ts',
      'workers/process-job.ts',
      'widgets/dashboard/stats/widget.tsx',
      'acl.ts',
      'setup.ts',
    ])
    touchFile(
      path.join(tmpDir, 'packages', 'core', 'src', 'modules', 'runtime_mod', 'subscribers', 'on-event.ts'),
      "export const metadata = { event: 'runtime.event' }\nexport default async function handler() {}\n"
    )
    touchFile(
      path.join(tmpDir, 'packages', 'core', 'src', 'modules', 'runtime_mod', 'workers', 'process-job.ts'),
      "export const metadata = { queue: 'runtime-jobs', concurrency: 2 }\nexport default async function handler() {}\n"
    )
    const enabled: ModuleEntry[] = [
      { id: 'runtime_mod', from: '@open-mercato/core' },
    ]
    const resolver = createMockResolver(tmpDir, enabled)
    const result = await generateModuleRegistryApp({ resolver, quiet: true })

    expect(result.errors).toEqual([])
    const output = readGenerated(tmpDir, 'modules.app.generated.ts')!
    expect(output).toContain('id: "runtime_mod"')
    expect(output).not.toContain('cli:')
    expect(output).toContain('subscribers:')
    expect(output).toContain('workers:')
    expect(output).toContain('createLazyModuleSubscriber')
    expect(output).toContain('createLazyModuleWorker')
    expect(output).toContain('dashboardWidgets:')
  })
})

describe('all generated files are valid with varying subsets', () => {
  it('produces all generated files even when no modules have matching content', async () => {
    scaffoldModule(tmpDir, 'bare_mod', 'pkg', ['acl.ts'])
    const enabled: ModuleEntry[] = [
      { id: 'bare_mod', from: '@open-mercato/core' },
    ]
    const resolver = createMockResolver(tmpDir, enabled)
    await generateModuleRegistry({ resolver, quiet: true })

    const expectedFiles = [
      'modules.generated.ts',
      'dashboard-widgets.generated.ts',
      'injection-widgets.generated.ts',
      'injection-tables.generated.ts',
      'search.generated.ts',
      'notifications.generated.ts',
      'ai-tools.generated.ts',
      'events.generated.ts',
      'analytics.generated.ts',
      'translations-fields.generated.ts',
      'frontend-middleware.generated.ts',
      'backend-middleware.generated.ts',
    ]
    for (const file of expectedFiles) {
      const content = readGenerated(tmpDir, file)
      expect(content).not.toBeNull()
      expect(content).toContain('AUTO-GENERATED')
    }
  })

  it('search.generated.ts has empty entries when no module provides search.ts', async () => {
    scaffoldModule(tmpDir, 'no_search', 'pkg', ['acl.ts'])
    const resolver = createMockResolver(tmpDir, [
      { id: 'no_search', from: '@open-mercato/core' },
    ])
    await generateModuleRegistry({ resolver, quiet: true })

    const search = readGenerated(tmpDir, 'search.generated.ts')!
    expect(search).toContain('const entriesRaw: SearchConfigEntry[] = []')
  })

  it('events.generated.ts has empty entries when no module provides events.ts', async () => {
    scaffoldModule(tmpDir, 'no_events', 'pkg', ['acl.ts'])
    const resolver = createMockResolver(tmpDir, [
      { id: 'no_events', from: '@open-mercato/core' },
    ])
    await generateModuleRegistry({ resolver, quiet: true })

    const events = readGenerated(tmpDir, 'events.generated.ts')!
    expect(events).toContain('const entriesRaw: EventConfigEntry[] = []')
  })

  it('translations-fields.generated.ts has empty entries when no module provides translations.ts', async () => {
    scaffoldModule(tmpDir, 'no_trans', 'pkg', ['acl.ts'])
    const resolver = createMockResolver(tmpDir, [
      { id: 'no_trans', from: '@open-mercato/core' },
    ])
    await generateModuleRegistry({ resolver, quiet: true })

    const transFields = readGenerated(tmpDir, 'translations-fields.generated.ts')!
    expect(transFields).not.toContain('no_trans')
  })

  it('ai-tools.generated.ts is empty when no module provides ai-tools.ts', async () => {
    scaffoldModule(tmpDir, 'no_ai', 'pkg', ['setup.ts'])
    const resolver = createMockResolver(tmpDir, [
      { id: 'no_ai', from: '@open-mercato/core' },
    ])
    await generateModuleRegistry({ resolver, quiet: true })

    const aiTools = readGenerated(tmpDir, 'ai-tools.generated.ts')!
    expect(aiTools).toContain('export const aiToolConfigEntries')
    expect(aiTools).not.toContain('no_ai')
  })

  it('security generated registries are empty when no module provides security convention files', async () => {
    scaffoldModule(tmpDir, 'no_security', 'pkg', ['setup.ts'])
    touchFile(
      path.join(tmpDir, 'packages', 'core', 'src', 'modules', 'no_security', 'generators.ts'),
      SECURITY_GENERATORS_CONTENT,
    )
    const resolver = createMockResolver(tmpDir, [
      { id: 'no_security', from: '@open-mercato/core' },
    ])
    await generateModuleRegistry({ resolver, quiet: true })

    const mfaProviders = readGenerated(tmpDir, 'security-mfa-providers.generated.ts')!
    const sudoTargets = readGenerated(tmpDir, 'security-sudo.generated.ts')!

    expect(mfaProviders).toContain('export const securityMfaProviderEntries')
    expect(mfaProviders).not.toContain('no_security')
    expect(sudoTargets).toContain('export const securitySudoTargetEntries')
    expect(sudoTargets).toContain('const entriesRaw: SecuritySudoTargetEntryRaw[] = [\n]')
    expect(sudoTargets).not.toContain('no_security')
  })

  it('discovers security convention files into dedicated generated registries', async () => {
    scaffoldModule(tmpDir, 'security_ext', 'pkg', [
      'security.mfa-providers.ts',
      'security.sudo.ts',
    ])
    touchFile(
      path.join(tmpDir, 'packages', 'core', 'src', 'modules', 'security_ext', 'generators.ts'),
      SECURITY_GENERATORS_CONTENT,
    )
    const resolver = createMockResolver(tmpDir, [
      { id: 'security_ext', from: '@open-mercato/core' },
    ])
    await generateModuleRegistry({ resolver, quiet: true })

    const mfaProviders = readGenerated(tmpDir, 'security-mfa-providers.generated.ts')!
    const sudoTargets = readGenerated(tmpDir, 'security-sudo.generated.ts')!

    expect(mfaProviders).toContain('security_ext')
    expect(mfaProviders).toContain('mfaProviders')
    expect(sudoTargets).toContain('security_ext')
    expect(sudoTargets).toContain('sudoTargets')
  })

  it('notifications.generated.ts uses typed fallback for legacy "types" export', async () => {
    scaffoldModule(tmpDir, 'notif_mod', 'pkg', ['notifications.ts'])
    const resolver = createMockResolver(tmpDir, [
      { id: 'notif_mod', from: '@open-mercato/core' },
    ])
    await generateModuleRegistry({ resolver, quiet: true })

    const notifications = readGenerated(tmpDir, 'notifications.generated.ts')!
    expect(notifications).toContain('"types"')
    expect(notifications).toContain('as NotificationTypeDefinition[]')
  })

  it('discovers frontend and backend middleware conventions', async () => {
    scaffoldModule(tmpDir, 'security', 'pkg', [
      'frontend/middleware.ts',
      'backend/middleware.ts',
    ])
    const resolver = createMockResolver(tmpDir, [
      { id: 'security', from: '@open-mercato/core' },
    ])
    await generateModuleRegistry({ resolver, quiet: true })

    const frontendMiddleware = readGenerated(tmpDir, 'frontend-middleware.generated.ts')!
    const backendMiddleware = readGenerated(tmpDir, 'backend-middleware.generated.ts')!
    expect(frontendMiddleware).toContain('moduleId: "security"')
    expect(backendMiddleware).toContain('moduleId: "security"')
  })
})
