export const DEFAULT_ENCRYPTION_MAPS: Array<{ entityId: string; fields: Array<{ field: string; hashField?: string | null }> }> = [
  {
    entityId: 'auth:user',
    fields: [{ field: 'email', hashField: 'email_hash' }],
  },
  {
    entityId: 'customers:customer_address',
    fields: [
      { field: 'name' },
      { field: 'company_name' },
      { field: 'address_line1' },
      { field: 'address_line2' },
      { field: 'city' },
      { field: 'region' },
      { field: 'postal_code' },
      { field: 'country' },
      { field: 'building_number' },
      { field: 'flat_number' },
    ],
  },
  {
    entityId: 'customers:customer_entity',
    fields: [
      { field: 'display_name' },
      { field: 'primary_email' },
      { field: 'primary_phone' },
      { field: 'next_interaction_name' },
      { field: 'description' },
    ],
  },
  {
    entityId: 'customers:customer_deal',
    fields: [
      { field: 'title' },
      { field: 'description' },
    ],
  },
  {
    entityId: 'customers:customer_activity',
    fields: [
      { field: 'subject' },
      { field: 'body' },
    ],
  },
  {
    entityId: 'customers:customer_comment',
    fields: [{ field: 'body' }],
  },
  {
    entityId: 'customers:customer_person_profile',
    fields: [
      { field: 'first_name' },
      { field: 'last_name' },
      { field: 'preferred_name' },
      { field: 'job_title' },
      { field: 'department' },
      { field: 'seniority' },
      { field: 'timezone' },
      { field: 'linked_in_url' },
      { field: 'twitter_url' },
    ],
  },
  {
    entityId: 'customers:customer_company_profile',
    fields: [
      { field: 'legal_name' },
      { field: 'brand_name' },
      { field: 'domain' },
      { field: 'website_url' },
      { field: 'industry' },
    ],
  },
  {
    entityId: 'sales:sales_order',
    fields: [
      { field: 'customer_snapshot' },
      { field: 'billing_address_snapshot' },
      { field: 'shipping_address_snapshot' },
      { field: 'shipping_method_snapshot' },
      { field: 'delivery_window_snapshot' },
      { field: 'payment_method_snapshot' },
      { field: 'totals_snapshot' },
      { field: 'catalog_snapshot' },
      { field: 'promotion_snapshot' },
      { field: 'comments' },
      { field: 'internal_notes' },
      { field: 'metadata' },
    ],
  },
  {
    entityId: 'sales:sales_quote',
    fields: [
      { field: 'customer_snapshot' },
      { field: 'billing_address_snapshot' },
      { field: 'shipping_address_snapshot' },
      { field: 'shipping_method_snapshot' },
      { field: 'delivery_window_snapshot' },
      { field: 'payment_method_snapshot' },
      { field: 'totals_snapshot' },
      { field: 'catalog_snapshot' },
      { field: 'promotion_snapshot' },
      { field: 'comments' },
      { field: 'internal_notes' },
      { field: 'metadata' },
    ],
  },
  {
    entityId: 'sales:sales_document_address',
    fields: [
      { field: 'name' },
      { field: 'purpose' },
      { field: 'company_name' },
      { field: 'address_line1' },
      { field: 'address_line2' },
      { field: 'city' },
      { field: 'region' },
      { field: 'postal_code' },
      { field: 'country' },
      { field: 'building_number' },
      { field: 'flat_number' },
    ],
  },
  {
    entityId: 'sales:sales_note',
    fields: [{ field: 'body' }],
  },
  {
    entityId: 'audit_logs:action_log',
    fields: [
      { field: 'command_id' },
      { field: 'action_label' },
      { field: 'command_payload' },
      { field: 'snapshot_before' },
      { field: 'snapshot_after' },
      { field: 'changes_json' },
      { field: 'context_json' },
    ],
  },
  {
    entityId: 'audit_logs:access_log',
    fields: [
      { field: 'resource_id' },
      { field: 'fields_json' },
      { field: 'context_json' },
    ],
  },
  {
    entityId: 'staff:staff_leave_request',
    fields: [
      { field: 'note' },
      { field: 'decision_comment' },
      { field: 'unavailability_reason_value' },
    ],
  },
  {
    entityId: 'vector:vector_search',
    fields: [
      { field: 'links' },
      { field: 'payload' },
      { field: 'result_title' },
      { field: 'result_subtitle' },
      { field: 'result_icon' },
      { field: 'result_badge' },
      { field: 'result_snapshot' },
      { field: 'primary_link_href' },
      { field: 'primary_link_label' },
    ],
  }
]
