import { Migration } from '@mikro-orm/migrations';

export class Migration20260319151615 extends Migration {

  override async up(): Promise<void> {
    this.addSql(`create table "checkout_links" ("id" uuid not null default gen_random_uuid(), "organization_id" uuid not null, "tenant_id" uuid not null, "name" text not null, "title" text null, "subtitle" text null, "description" text null, "logo_attachment_id" uuid null, "logo_url" text null, "primary_color" text null, "secondary_color" text null, "background_color" text null, "theme_mode" text not null default 'auto', "pricing_mode" text not null, "fixed_price_amount" numeric(12,2) null, "fixed_price_currency_code" text null, "fixed_price_includes_tax" boolean not null default true, "fixed_price_original_amount" numeric(12,2) null, "custom_amount_min" numeric(12,2) null, "custom_amount_max" numeric(12,2) null, "custom_amount_currency_code" text null, "price_list_items" jsonb null, "gateway_provider_key" text null, "gateway_settings" jsonb null, "customer_fields_schema" jsonb null, "legal_documents" jsonb null, "display_custom_fields_on_page" boolean not null default false, "success_title" text null, "success_message" text null, "cancel_title" text null, "cancel_message" text null, "error_title" text null, "error_message" text null, "success_email_subject" text null, "success_email_body" text null, "error_email_subject" text null, "error_email_body" text null, "start_email_subject" text null, "start_email_body" text null, "password_hash" text null, "max_completions" int null, "status" text not null default 'draft', "checkout_type" text not null default 'pay_link', "created_at" timestamptz not null, "updated_at" timestamptz not null, "deleted_at" timestamptz null, "template_id" uuid null, "slug" text not null, "completion_count" int not null default 0, "active_reservation_count" int not null default 0, "is_locked" boolean not null default false, constraint "checkout_links_pkey" primary key ("id"));`);
    this.addSql(`create index "checkout_links_organization_id_tenant_id_deleted_at_index" on "checkout_links" ("organization_id", "tenant_id", "deleted_at");`);
    this.addSql(`create unique index "checkout_links_slug_index" on "checkout_links" ("slug") where deleted_at is null;`);
    this.addSql(`create index "checkout_links_organization_id_tenant_id_status_de_49f3b_index" on "checkout_links" ("organization_id", "tenant_id", "status", "deleted_at");`);

    this.addSql(`create table "checkout_link_templates" ("id" uuid not null default gen_random_uuid(), "organization_id" uuid not null, "tenant_id" uuid not null, "name" text not null, "title" text null, "subtitle" text null, "description" text null, "logo_attachment_id" uuid null, "logo_url" text null, "primary_color" text null, "secondary_color" text null, "background_color" text null, "theme_mode" text not null default 'auto', "pricing_mode" text not null, "fixed_price_amount" numeric(12,2) null, "fixed_price_currency_code" text null, "fixed_price_includes_tax" boolean not null default true, "fixed_price_original_amount" numeric(12,2) null, "custom_amount_min" numeric(12,2) null, "custom_amount_max" numeric(12,2) null, "custom_amount_currency_code" text null, "price_list_items" jsonb null, "gateway_provider_key" text null, "gateway_settings" jsonb null, "customer_fields_schema" jsonb null, "legal_documents" jsonb null, "display_custom_fields_on_page" boolean not null default false, "success_title" text null, "success_message" text null, "cancel_title" text null, "cancel_message" text null, "error_title" text null, "error_message" text null, "success_email_subject" text null, "success_email_body" text null, "error_email_subject" text null, "error_email_body" text null, "start_email_subject" text null, "start_email_body" text null, "password_hash" text null, "max_completions" int null, "status" text not null default 'draft', "checkout_type" text not null default 'pay_link', "created_at" timestamptz not null, "updated_at" timestamptz not null, "deleted_at" timestamptz null, constraint "checkout_link_templates_pkey" primary key ("id"));`);
    this.addSql(`create index "checkout_link_templates_organization_id_tenant_id__9eeb6_index" on "checkout_link_templates" ("organization_id", "tenant_id", "deleted_at");`);

    this.addSql(`create table "checkout_transactions" ("id" uuid not null default gen_random_uuid(), "organization_id" uuid not null, "tenant_id" uuid not null, "link_id" uuid not null, "status" text not null, "amount" numeric(12,2) not null, "currency_code" text not null, "idempotency_key" text not null, "customer_data" jsonb null, "first_name" text null, "last_name" text null, "email" text null, "phone" text null, "gateway_transaction_id" uuid null, "payment_status" text null, "selected_price_item_id" text null, "accepted_legal_consents" jsonb null, "ip_address" text null, "user_agent" text null, "created_at" timestamptz not null, "updated_at" timestamptz not null, constraint "checkout_transactions_pkey" primary key ("id"));`);
    this.addSql(`create unique index "checkout_transactions_organization_id_tenant_id_li_7548d_index" on "checkout_transactions" ("organization_id", "tenant_id", "link_id", "idempotency_key");`);
    this.addSql(`create index "checkout_transactions_gateway_transaction_id_index" on "checkout_transactions" ("gateway_transaction_id");`);
    this.addSql(`create index "checkout_transactions_organization_id_tenant_id_cr_d105e_index" on "checkout_transactions" ("organization_id", "tenant_id", "created_at");`);
    this.addSql(`create index "checkout_transactions_organization_id_tenant_id_li_e6e13_index" on "checkout_transactions" ("organization_id", "tenant_id", "link_id", "status");`);
  }

}
