import fs from 'node:fs'
import path from 'node:path'
import ts from 'typescript'
import { VariableDeclarationKind } from 'ts-morph'
import type { PackageResolver, ModuleEntry } from '../resolver'
import { MODULE_CODE_EXTENSIONS } from './scanner'
import {
  calculateChecksum,
  readChecksumRecord,
  writeChecksumRecord,
  ensureDir,
  toVar,
  toSnake,
  rimrafDir,
  logGenerationResult,
  type GeneratorResult,
  createGeneratorResult,
} from '../utils'
import { addAutoGeneratedComment, createGeneratedSourceFile, elementAccess, getSourceText, identifier, returnStatement } from './ast'

type GroupKey = '@app' | '@open-mercato/core' | string
type EntityFieldMap = Record<string, string[]>

export interface EntityIdsOptions {
  resolver: PackageResolver
  quiet?: boolean
}

/**
 * Extract exported class names from a TypeScript source file without dynamic import.
 * This is used for @app modules since Node.js can't import TypeScript files directly.
 */
function parseExportedClassNamesFromFile(filePath: string): string[] {
  const src = fs.readFileSync(filePath, 'utf8')
  const sf = ts.createSourceFile(filePath, src, ts.ScriptTarget.ES2020, true, ts.ScriptKind.TS)
  const classNames: string[] = []

  sf.forEachChild((node) => {
    // Check for exported class declarations
    if (ts.isClassDeclaration(node) && node.name) {
      const hasExport = node.modifiers?.some(
        (m) => m.kind === ts.SyntaxKind.ExportKeyword
      )
      if (hasExport) {
        classNames.push(node.name.text)
      }
    }
  })

  return classNames
}

function unwrapObjectLiteralExpression(
  expression: ts.Expression | undefined,
): ts.ObjectLiteralExpression | undefined {
  if (!expression) return undefined
  if (ts.isObjectLiteralExpression(expression)) return expression
  if (ts.isAsExpression(expression) || ts.isTypeAssertionExpression(expression)) {
    return unwrapObjectLiteralExpression(expression.expression)
  }
  if (ts.isParenthesizedExpression(expression)) {
    return unwrapObjectLiteralExpression(expression.expression)
  }
  return undefined
}

function readPropertyInitializer(
  objectLiteral: ts.ObjectLiteralExpression,
  propertyName: string,
): ts.Expression | undefined {
  for (const property of objectLiteral.properties) {
    if (!ts.isPropertyAssignment(property)) continue
    const name = ts.isIdentifier(property.name)
      ? property.name.text
      : ts.isStringLiteralLike(property.name)
        ? property.name.text
        : undefined
    if (name === propertyName) {
      return property.initializer
    }
  }
  return undefined
}

function parseGeneratedModuleEntityNames(filePath: string, moduleId: string): string[] {
  if (!fs.existsSync(filePath)) return []

  const source = fs.readFileSync(filePath, 'utf8')
  const scriptKind = filePath.endsWith('.js') ? ts.ScriptKind.JS : ts.ScriptKind.TS
  const sf = ts.createSourceFile(filePath, source, ts.ScriptTarget.ES2020, true, scriptKind)

  for (const statement of sf.statements) {
    if (!ts.isVariableStatement(statement)) continue
    const declaration = statement.declarationList.declarations.find((candidate) =>
      ts.isIdentifier(candidate.name) && candidate.name.text === 'E')
    if (!declaration) continue

    const eObject = unwrapObjectLiteralExpression(declaration.initializer)
    if (!eObject) continue

    const moduleObject = unwrapObjectLiteralExpression(readPropertyInitializer(eObject, moduleId))
    if (!moduleObject) return []

    const names: string[] = []
    for (const property of moduleObject.properties) {
      if (!ts.isPropertyAssignment(property)) continue
      const name = ts.isIdentifier(property.name)
        ? property.name.text
        : ts.isStringLiteralLike(property.name)
          ? property.name.text
          : undefined
      if (name) names.push(name)
    }
    return names
  }

  return []
}

function parseGeneratedEntityFieldsFile(filePath: string): string[] {
  if (!fs.existsSync(filePath)) return []

  const source = fs.readFileSync(filePath, 'utf8')
  const scriptKind = filePath.endsWith('.js') ? ts.ScriptKind.JS : ts.ScriptKind.TS
  const sf = ts.createSourceFile(filePath, source, ts.ScriptTarget.ES2020, true, scriptKind)
  const fields: string[] = []

  for (const statement of sf.statements) {
    if (!ts.isVariableStatement(statement)) continue
    for (const declaration of statement.declarationList.declarations) {
      if (!ts.isIdentifier(declaration.name) || !declaration.initializer) continue
      if (!ts.isStringLiteralLike(declaration.initializer)) continue
      fields.push(declaration.initializer.text)
    }
  }

  return Array.from(new Set(fields))
}

function resolveExistingFile(candidates: string[]): string | null {
  for (const candidate of candidates) {
    if (fs.existsSync(candidate)) return candidate
  }
  return null
}

function loadStandaloneGeneratedPackageEntities(
  resolver: PackageResolver,
  entry: ModuleEntry,
): { entityNames: string[]; entityFieldMap: EntityFieldMap } | null {
  if (resolver.isMonorepo() || !entry.from || entry.from === '@app') return null

  const packageRoot = resolver.getPackageRoot(entry.from)
  const generatedRoot = fs.existsSync(path.join(packageRoot, 'generated'))
    ? path.join(packageRoot, 'generated')
    : path.join(packageRoot, 'dist', 'generated')
  const idsFile = resolveExistingFile([
    path.join(generatedRoot, 'entities.ids.generated.ts'),
    path.join(generatedRoot, 'entities.ids.generated.js'),
  ])
  if (!idsFile) return null
  const entityNames = parseGeneratedModuleEntityNames(idsFile, entry.id)

  if (entityNames.length === 0) return null

  const entityFieldMap: EntityFieldMap = {}
  for (const entityName of entityNames) {
    const fieldsFile = resolveExistingFile([
      path.join(generatedRoot, 'entities', entityName, 'index.ts'),
      path.join(generatedRoot, 'entities', entityName, 'index.js'),
    ])
    if (!fieldsFile) continue
    const fields = parseGeneratedEntityFieldsFile(fieldsFile)
    entityFieldMap[entityName] = fields
  }

  return { entityNames, entityFieldMap }
}

function parseEntityFieldsFromFile(filePath: string, exportedClassNames: string[]): EntityFieldMap {
  const src = fs.readFileSync(filePath, 'utf8')
  const sf = ts.createSourceFile(filePath, src, ts.ScriptTarget.ES2020, true, ts.ScriptKind.TS)

  const exported = new Set(exportedClassNames)
  const result: EntityFieldMap = {}

  function getDecoratorArgNameLiteral(dec: ts.Decorator | undefined): string | undefined {
    if (!dec) return undefined
    const expr = dec.expression
    if (!ts.isCallExpression(expr)) return undefined
    if (!expr.arguments.length) return undefined
    const first = expr.arguments[0]
    if (!ts.isObjectLiteralExpression(first)) return undefined
    for (const prop of first.properties) {
      if (ts.isPropertyAssignment(prop) && ts.isIdentifier(prop.name) && prop.name.text === 'name') {
        if (ts.isStringLiteral(prop.initializer)) return prop.initializer.text
      }
    }
    return undefined
  }

  function normalizeDbName(propertyName: string, _decoratorName?: string, nameOverride?: string): string {
    if (nameOverride) return nameOverride
    return toSnake(propertyName)
  }

  sf.forEachChild((node) => {
    if (!ts.isClassDeclaration(node) || !node.name) return
    const clsName = node.name.text
    if (!exported.has(clsName)) return
    const entityKey = toSnake(clsName)
    const fields: string[] = []

    for (const member of node.members) {
      if (!ts.isPropertyDeclaration(member) || !member.name) continue
      const name = ts.isIdentifier(member.name)
        ? member.name.text
        : ts.isStringLiteral(member.name)
          ? member.name.text
          : undefined
      if (!name) continue
      if (member.modifiers?.some((m) => m.kind === ts.SyntaxKind.StaticKeyword)) continue
      const decorators = ts.canHaveDecorators(member)
        ? ts.getDecorators(member) ?? []
        : []
      let dbName: string | undefined
      if (decorators && decorators.length) {
        for (const d of decorators) {
          const nameOverride = getDecoratorArgNameLiteral(d)
          dbName = normalizeDbName(name, undefined, nameOverride)
          if (dbName) break
        }
      }
      if (!dbName) dbName = normalizeDbName(name)
      fields.push(dbName)
    }
    result[entityKey] = Array.from(new Set(fields))
  })

  return result
}

function writePerEntityFieldFiles(outRoot: string, fieldsByEntity: EntityFieldMap): void {
  fs.mkdirSync(outRoot, { recursive: true })
  const desiredEntities = new Set(Object.keys(fieldsByEntity))
  for (const [entity, fields] of Object.entries(fieldsByEntity)) {
    const entDir = path.join(outRoot, entity)
    fs.mkdirSync(entDir, { recursive: true })
    const sourceFile = createGeneratedSourceFile(`${entity}/index.ts`)
    for (const field of fields) {
      sourceFile.addVariableStatement({
        declarationKind: VariableDeclarationKind.Const,
        isExported: true,
        declarations: [
          {
            name: toVar(field),
            initializer: JSON.stringify(field),
          },
        ],
      })
    }
    fs.writeFileSync(path.join(entDir, 'index.ts'), getSourceText(sourceFile))
  }

  const existingEntries = fs.existsSync(outRoot) ? fs.readdirSync(outRoot, { withFileTypes: true }) : []
  for (const entry of existingEntries) {
    if (!entry.isDirectory()) continue
    if (desiredEntities.has(entry.name)) continue
    rimrafDir(path.join(outRoot, entry.name))
  }
}

function writeEntityFieldsRegistry(generatedRoot: string, fieldsByEntity: EntityFieldMap): void {
  const entities = Object.keys(fieldsByEntity).sort((a, b) => a.localeCompare(b))
  const registry: Record<string, Record<string, string>> = {}
  for (const entity of entities) {
    registry[toVar(entity)] = {}
    for (const field of fieldsByEntity[entity] ?? []) {
      registry[toVar(entity)][toVar(field)] = field
    }
  }

  const sourceFile = createGeneratedSourceFile('entity-fields-registry.ts')
  addAutoGeneratedComment(sourceFile, 'entity-ids')
  sourceFile.insertText(sourceFile.getFullText().length, '// Static registry for entity fields - eliminates dynamic imports for Turbopack compatibility\n')
  sourceFile.addVariableStatement({
    declarationKind: VariableDeclarationKind.Const,
    isExported: true,
    declarations: [
      {
        name: 'entityFieldsRegistry',
        type: 'Record<string, Record<string, string>>',
        initializer: JSON.stringify(registry, null, 2),
      },
    ],
  })
  sourceFile.addFunction({
    name: 'getEntityFields',
    isExported: true,
    parameters: [{ name: 'slug', type: 'string' }],
    returnType: 'Record<string, string> | undefined',
    statements: [returnStatement(elementAccess(identifier('entityFieldsRegistry'), identifier('slug')))],
  })
  const outPath = path.join(generatedRoot, 'entity-fields-registry.ts')
  ensureDir(outPath)
  fs.writeFileSync(outPath, getSourceText(sourceFile))
}

export async function generateEntityIds(options: EntityIdsOptions): Promise<GeneratorResult> {
  const { resolver, quiet = false } = options
  const result = createGeneratorResult()

  const outputDir = resolver.getOutputDir()
  const outFile = path.join(outputDir, 'entities.ids.generated.ts')
  const checksumFile = path.join(outputDir, 'entities.ids.generated.checksum')

  const entries = resolver.loadEnabledModules()

  const consolidated: Record<string, Record<string, string>> = {}
  const grouped: Record<GroupKey, Record<string, Record<string, string>>> = {}
  const modulesDict: Record<string, string> = {}
  const groupedModulesDict: Record<GroupKey, Record<string, string>> = {}

  const fieldsByGroup: Record<GroupKey, Record<string, EntityFieldMap>> = {}

  for (const entry of entries) {
    const modId = entry.id
    const roots = resolver.getModulePaths(entry)
    const imps = resolver.getModuleImportBase(entry)
    const group: GroupKey = (entry.from as GroupKey) || '@open-mercato/core'

    const standaloneGeneratedPackageEntities = loadStandaloneGeneratedPackageEntities(resolver, entry)

    // Locate entities definition file (prefer app override)
    const appData = path.join(roots.appBase, 'data')
    const pkgData = path.join(roots.pkgBase, 'data')
    const appDb = path.join(roots.appBase, 'db')
    const pkgDb = path.join(roots.pkgBase, 'db')
    const bases = [appData, pkgData, appDb, pkgDb]
    const candidates = ['entities.override', 'entities', 'schema']
    let importPath: string | null = null
    let filePath: string | null = null

    for (const base of bases) {
      for (const f of candidates) {
        const p = resolveConventionFile(base, f)
        if (p) {
          const fromApp = base.startsWith(roots.appBase)
          const sub = path.basename(base) // 'data' | 'db'
          importPath = `${fromApp ? imps.appBase : imps.pkgBase}/${sub}/${f}`
          filePath = p
          break
        }
      }
      if (importPath) break
    }

    // No entities file found -> still register module id
    if (!filePath && !standaloneGeneratedPackageEntities) {
      modulesDict[modId] = modId
      groupedModulesDict[group] = groupedModulesDict[group] || {}
      groupedModulesDict[group][modId] = modId
      continue
    }

    const exportNames = filePath ? parseExportedClassNamesFromFile(filePath) : []

    const entityNames = standaloneGeneratedPackageEntities
      ? standaloneGeneratedPackageEntities.entityNames
      : exportNames
        .map((k) => toSnake(k))
        .filter((k, idx, arr) => arr.indexOf(k) === idx)

    // Build dictionaries
    modulesDict[modId] = modId
    groupedModulesDict[group] = groupedModulesDict[group] || {}
    groupedModulesDict[group][modId] = modId

    consolidated[modId] = consolidated[modId] || {}
    grouped[group] = grouped[group] || {}
    grouped[group][modId] = grouped[group][modId] || {}

    for (const en of entityNames) {
      consolidated[modId][en] = `${modId}:${en}`
      grouped[group][modId][en] = `${modId}:${en}`
    }

    // Parse entity fields from TypeScript source
    const entityFieldMap = standaloneGeneratedPackageEntities
      ? standaloneGeneratedPackageEntities.entityFieldMap
      : parseEntityFieldsFromFile(filePath!, exportNames)
    fieldsByGroup[group] = fieldsByGroup[group] || {}
    fieldsByGroup[group][modId] = entityFieldMap
  }

  // Write consolidated output
  const consolidatedSourceFile = createGeneratedSourceFile('entities.ids.generated.ts')
  addAutoGeneratedComment(consolidatedSourceFile, 'entity-ids')
  consolidatedSourceFile.addVariableStatement({
    declarationKind: VariableDeclarationKind.Const,
    isExported: true,
    declarations: [
      { name: 'M', initializer: `${JSON.stringify(modulesDict, null, 2)} as const` },
      { name: 'E', initializer: `${JSON.stringify(consolidated, null, 2)} as const` },
    ],
  })
  consolidatedSourceFile.addTypeAlias({
    name: 'KnownModuleId',
    isExported: true,
    type: 'keyof typeof M',
  })
  consolidatedSourceFile.addTypeAlias({
    name: 'KnownEntities',
    isExported: true,
    type: 'typeof E',
  })
  const consolidatedSrc = getSourceText(consolidatedSourceFile)

  // Check if content has changed
  const newChecksum = calculateChecksum(consolidatedSrc)
  let shouldWrite = true

  const existingRecord = readChecksumRecord(checksumFile)
  if (existingRecord && existingRecord.content === newChecksum) {
    shouldWrite = false
  }

  if (shouldWrite) {
    ensureDir(outFile)
    fs.writeFileSync(outFile, consolidatedSrc)
    writeChecksumRecord(checksumFile, { content: newChecksum, structure: '' })
    result.filesWritten.push(outFile)
    if (!quiet) {
      logGenerationResult(path.relative(process.cwd(), outFile), true)
    }
  } else {
    result.filesUnchanged.push(outFile)
  }

  // Write per-group outputs
  const groups = Object.keys(grouped) as GroupKey[]
  for (const g of groups) {
    if (!resolver.isMonorepo() && g !== '@app') {
      continue
    }

    const pkgOutputDir = resolver.getPackageOutputDir(g)
    // Skip @app group since it writes to the same location as the consolidated output
    if (g === '@app' && pkgOutputDir === outputDir) {
      continue
    }
    const out = path.join(pkgOutputDir, 'entities.ids.generated.ts')

    const groupSourceFile = createGeneratedSourceFile(`${String(g)}/entities.ids.generated.ts`)
    addAutoGeneratedComment(groupSourceFile, 'entity-ids')
    groupSourceFile.addVariableStatement({
      declarationKind: VariableDeclarationKind.Const,
      isExported: true,
      declarations: [
        { name: 'M', initializer: `${JSON.stringify(groupedModulesDict[g] || {}, null, 2)} as const` },
        { name: 'E', initializer: `${JSON.stringify(grouped[g] || {}, null, 2)} as const` },
      ],
    })
    groupSourceFile.addTypeAlias({
      name: 'KnownModuleId',
      isExported: true,
      type: 'keyof typeof M',
    })
    groupSourceFile.addTypeAlias({
      name: 'KnownEntities',
      isExported: true,
      type: 'typeof E',
    })
    const src = getSourceText(groupSourceFile)
    ensureDir(out)
    fs.writeFileSync(out, src)
    result.filesWritten.push(out)

    const fieldsRoot = path.join(pkgOutputDir, 'entities')
    const fieldsByModule = fieldsByGroup[g] || {}
    const combined: EntityFieldMap = {}
    for (const mId of Object.keys(fieldsByModule)) {
      const mMap = fieldsByModule[mId]
      for (const [entity, fields] of Object.entries(mMap)) {
        combined[entity] = Array.from(new Set([...(combined[entity] || []), ...fields]))
      }
    }
    writePerEntityFieldFiles(fieldsRoot, combined)

    // Generate static entity fields registry for Turbopack compatibility
    writeEntityFieldsRegistry(pkgOutputDir, combined)
  }

  // Write combined entity fields to root generated/ folder
  const combinedAll: EntityFieldMap = {}
  for (const groupFields of Object.values(fieldsByGroup)) {
    for (const mMap of Object.values(groupFields)) {
      for (const [entity, fields] of Object.entries(mMap)) {
        combinedAll[entity] = Array.from(new Set([...(combinedAll[entity] || []), ...fields]))
      }
    }
  }
  writePerEntityFieldFiles(path.join(outputDir, 'entities'), combinedAll)
  writeEntityFieldsRegistry(outputDir, combinedAll)

  return result
}

function resolveConventionFile(baseDir: string, basename: string): string | null {
  for (const extension of MODULE_CODE_EXTENSIONS) {
    const candidate = path.join(baseDir, `${basename}${extension}`)
    if (fs.existsSync(candidate)) return candidate
  }
  return null
}
