import fs from 'node:fs'
import path from 'node:path'
import { StructureKind, VariableDeclarationKind } from 'ts-morph'
import type { PackageResolver } from '../resolver'
import { MODULE_CODE_EXTENSIONS } from './scanner'
import {
  calculateChecksum,
  readChecksumRecord,
  writeChecksumRecord,
  ensureDir,
  toVar,
  logGenerationResult,
  type GeneratorResult,
  createGeneratorResult,
} from '../utils'
import {
  addAutoGeneratedComment,
  addImportSpec,
  arrayLiteral,
  createGeneratedSourceFile,
  getSourceText,
  identifier,
  methodCall,
  parenthesized,
} from './ast'

export interface ModuleDiOptions {
  resolver: PackageResolver
  quiet?: boolean
}

export async function generateModuleDi(options: ModuleDiOptions): Promise<GeneratorResult> {
  const { resolver, quiet = false } = options
  const result = createGeneratorResult()

  const outputDir = resolver.getOutputDir()
  const outFile = path.join(outputDir, 'di.generated.ts')
  const checksumFile = path.join(outputDir, 'di.generated.checksum')

  const mods = resolver.loadEnabledModules()
  const imports: Array<{ name: string; moduleSpecifier: string }> = []
  const registrars: string[] = []
  let i = 0

  for (const entry of mods) {
    const modId = entry.id
    const roots = resolver.getModulePaths(entry)
    const imp = resolver.getModuleImportBase(entry)
    const isAppModule = entry.from === '@app'

    const useApp = resolveModuleConventionFile(roots.appBase, 'di')
    const usePkg = resolveModuleConventionFile(roots.pkgBase, 'di')
    const importName = `D_${toVar(modId)}_${i++}`

    if (useApp) {
      // For @app modules, use relative path to work in both Next.js and Node.js CLI context
      // From .mercato/generated/, go up two levels (../..) to reach the app root, then into src/modules/
      const importPath = isAppModule ? `../../src/modules/${modId}/di` : `${imp.appBase}/di`
      imports.push({ name: importName, moduleSpecifier: importPath })
      registrars.push(`${importName}.register`)
    } else if (usePkg) {
      imports.push({ name: importName, moduleSpecifier: `${imp.pkgBase}/di` })
      registrars.push(`${importName}.register`)
    }
  }

  const sourceFile = createGeneratedSourceFile('di.generated.ts')
  addAutoGeneratedComment(sourceFile, 'di')
  imports.forEach((entry) => {
    addImportSpec(sourceFile, {
      kind: StructureKind.ImportDeclaration,
      namespaceImport: entry.name,
      moduleSpecifier: entry.moduleSpecifier,
    })
  })
  sourceFile.addVariableStatement({
    declarationKind: VariableDeclarationKind.Const,
    declarations: [
      {
        name: 'diRegistrars',
        type: '(((c: any) => void) | undefined)[]',
        initializer: methodCall(
          parenthesized(arrayLiteral(registrars, (currentWriter, registrar) => identifier(registrar)(currentWriter))),
          'filter',
          [identifier('Boolean')],
        ),
      },
    ],
  })
  sourceFile.addExportDeclaration({
    namedExports: ['diRegistrars'],
  })
  sourceFile.addExportAssignment({
    isExportEquals: false,
    expression: 'diRegistrars',
  })
  const output = getSourceText(sourceFile)

  // Check if content has changed
  const newChecksum = calculateChecksum(output)
  let shouldWrite = true

  const existingRecord = readChecksumRecord(checksumFile)
  if (existingRecord && existingRecord.content === newChecksum) {
    shouldWrite = false
  }

  if (shouldWrite) {
    ensureDir(outFile)
    fs.writeFileSync(outFile, output)
    writeChecksumRecord(checksumFile, { content: newChecksum, structure: '' })
    result.filesWritten.push(outFile)
    if (!quiet) {
      logGenerationResult(path.relative(process.cwd(), outFile), true)
    }
  } else {
    result.filesUnchanged.push(outFile)
  }

  return result
}

function resolveModuleConventionFile(baseDir: string, basename: string): boolean {
  return MODULE_CODE_EXTENSIONS.some((extension) => fs.existsSync(path.join(baseDir, `${basename}${extension}`)))
}
