import fs from 'node:fs'
import path from 'node:path'
import { StructureKind, VariableDeclarationKind } from 'ts-morph'
import type { PackageResolver } from '../resolver'
import { MODULE_CODE_EXTENSIONS, stripModuleCodeExtension } from './scanner'
import {
  calculateChecksum,
  readChecksumRecord,
  writeChecksumRecord,
  ensureDir,
  toVar,
  logGenerationResult,
  type GeneratorResult,
  createGeneratorResult,
} from '../utils'
import {
  addAutoGeneratedComment,
  addImportSpec,
  asExpression,
  arrayLiteral,
  arrowFunction,
  binaryExpression,
  callExpression,
  createGeneratedSourceFile,
  expressionStatement,
  getSourceText,
  identifier,
  ifStatement,
  logicalAnd,
  methodCall,
  objectEntries,
  objectLiteral,
  prefixExpression,
  propertyAccess,
  returnStatement,
  spreadExpression,
  templateLiteral,
  variableStatement,
} from './ast'

export interface ModuleEntitiesOptions {
  resolver: PackageResolver
  quiet?: boolean
}

export async function generateModuleEntities(options: ModuleEntitiesOptions): Promise<GeneratorResult> {
  const { resolver, quiet = false } = options
  const result = createGeneratorResult()

  const outputDir = resolver.getOutputDir()
  const outFile = path.join(outputDir, 'entities.generated.ts')
  const checksumFile = path.join(outputDir, 'entities.generated.checksum')

  const mods = resolver.loadEnabledModules()
  const imports: Array<{ name: string; moduleSpecifier: string }> = []
  const entitySources: Array<{ importName: string; moduleId: string }> = []
  let n = 0

  for (const entry of mods) {
    const modId = entry.id
    const roots = resolver.getModulePaths(entry)
    const imp = resolver.getModuleImportBase(entry)
    const isAppModule = entry.from === '@app'

    // prefer app override data/, fallback to core data/, then legacy db/
    const appData = path.join(roots.appBase, 'data')
    const pkgData = path.join(roots.pkgBase, 'data')
    const appDb = path.join(roots.appBase, 'db')
    const pkgDb = path.join(roots.pkgBase, 'db')
    const bases = [appData, pkgData, appDb, pkgDb]
    const candidates = ['entities.override', 'entities', 'schema']

    let found: { base: string; file: string } | null = null
    for (const base of bases) {
      for (const f of candidates) {
        const p = resolveConventionFile(base, f)
        if (p) {
          found = { base, file: path.basename(p) }
          break
        }
      }
      if (found) break
    }
    if (!found) continue

    const importName = `E_${toVar(modId)}_${n++}`
    const sub = path.basename(found.base) // 'data' or 'db'
    const fromApp = found.base.startsWith(roots.appBase)
    // For @app modules, use relative path to ensure it works both in Next.js and Node.js CLI context
    // From .mercato/generated/, the relative path to src/modules/ is ../src/modules/
    let relImport: string
    if (isAppModule && fromApp) {
      // From .mercato/generated/, go up two levels (../..) to reach the app root, then into src/modules/
      relImport = `../../src/modules/${modId}/${sub}/${stripModuleCodeExtension(found.file)}`
    } else {
      const baseImport = fromApp ? imp.appBase : imp.pkgBase
      relImport = `${baseImport}/${sub}/${stripModuleCodeExtension(found.file)}`
    }
    imports.push({ name: importName, moduleSpecifier: relImport })
    entitySources.push({ importName, moduleId: modId })
  }

  const sourceFile = createGeneratedSourceFile('entities.generated.ts')
  addAutoGeneratedComment(sourceFile, 'entities')
  imports.forEach((entry) => {
    addImportSpec(sourceFile, {
      kind: StructureKind.ImportDeclaration,
      namespaceImport: entry.name,
      moduleSpecifier: entry.moduleSpecifier,
    })
  })
  sourceFile.addFunction({
    name: 'enhanceEntities',
    parameters: [
      { name: 'namespace', type: 'Record<string, unknown>' },
      { name: 'moduleId', type: 'string' },
    ],
    returnType: 'any[]',
    statements: [
      returnStatement(
        methodCall(
          methodCall(objectEntries(identifier('namespace')), 'filter', [
            arrowFunction({
              parameters: ['[, value]'],
              body: binaryExpression(
                prefixExpression('typeof ', identifier('value')),
                '===',
                'function',
              ),
            }),
          ]),
          'map',
          [
            arrowFunction({
              parameters: ['[exportName, value]'],
              body: (writer) => {
                writer.block(() => {
                  variableStatement({
                    name: 'entity',
                    initializer: asExpression(identifier('value'), '{ entityName?: string }'),
                  })(writer)
                  writer.newLine()
                  ifStatement({
                    condition: logicalAnd([
                      identifier('entity'),
                      binaryExpression(
                        prefixExpression('typeof ', identifier('entity')),
                        '===',
                        'function',
                      ),
                      binaryExpression(
                        methodCall(
                          propertyAccess(
                            propertyAccess(identifier('Object'), 'prototype'),
                            'hasOwnProperty',
                          ),
                          'call',
                          [identifier('entity'), 'entityName'],
                        ),
                        '===',
                        false,
                      ),
                    ]),
                    thenStatements: [
                      expressionStatement(
                        callExpression(propertyAccess(identifier('Object'), 'defineProperty'), [
                          identifier('entity'),
                          'entityName',
                          objectLiteral([
                            {
                              name: 'value',
                              value: templateLiteral([
                                identifier('moduleId'),
                                '.',
                                identifier('exportName'),
                              ]),
                            },
                            { name: 'configurable', value: true },
                            { name: 'enumerable', value: false },
                            { name: 'writable', value: false },
                          ]),
                        ]),
                      ),
                    ],
                  })(writer)
                  writer.newLine()
                  returnStatement(identifier('entity'))(writer)
                })
              },
            }),
          ],
        ),
      ),
    ],
  })
  sourceFile.addVariableStatement({
    declarationKind: VariableDeclarationKind.Const,
    isExported: true,
    declarations: [
      {
        name: 'entities',
        initializer: arrayLiteral(entitySources, (writer, entry) =>
          spreadExpression(callExpression(identifier('enhanceEntities'), [identifier(entry.importName), entry.moduleId]))(writer)),
      },
    ],
  })
  const output = getSourceText(sourceFile)

  // Check if content has changed
  const newChecksum = calculateChecksum(output)
  let shouldWrite = true

  const existingRecord = readChecksumRecord(checksumFile)
  if (existingRecord && existingRecord.content === newChecksum) {
    shouldWrite = false
  }

  if (shouldWrite) {
    ensureDir(outFile)
    fs.writeFileSync(outFile, output)
    writeChecksumRecord(checksumFile, { content: newChecksum, structure: '' })
    result.filesWritten.push(outFile)
    if (!quiet) {
      logGenerationResult(path.relative(process.cwd(), outFile), true)
    }
  } else {
    result.filesUnchanged.push(outFile)
  }

  return result
}

function resolveConventionFile(baseDir: string, basename: string): string | null {
  for (const extension of MODULE_CODE_EXTENSIONS) {
    const candidate = path.join(baseDir, `${basename}${extension}`)
    if (fs.existsSync(candidate)) return candidate
  }
  return null
}
