/* eslint-disable */
// AUTO-GENERATED by @open-mercato/ui build. Do not edit by hand.
// Generated from discovered icon string usages across the repo.

import type * as React from 'react'
import type { LucideIcon } from 'lucide-react'
import {
  AlertCircle,
  AlertTriangle,
  BadgeCheck,
  BarChart2,
  Bell,
  Bolt,
  Box,
  Briefcase,
  BriefcaseBusiness,
  Building,
  Building2,
  Calendar,
  CalendarCheck,
  CalendarClock,
  CalendarOff,
  CalendarX,
  Check,
  CheckCircle,
  CheckSquare,
  ClipboardList,
  Clock,
  Clock3,
  Coins,
  Copy,
  CreditCard,
  Database,
  DollarSign,
  Download,
  ExternalLink,
  FileMinus,
  FileText,
  FilterX,
  FolderTree,
  GitBranch,
  GitCompareArrows,
  GitPullRequestArrow,
  Handshake,
  Heart,
  Inbox,
  Key,
  KeyRound,
  Layers,
  LineChart,
  List,
  Lock,
  Mail,
  MailOpen,
  MapPin,
  Package,
  PackagePlus,
  PackageX,
  Percent,
  PieChart,
  PlusSquare,
  Receipt,
  ReceiptText,
  Reply,
  Ruler,
  Settings,
  Shapes,
  Shield,
  ShieldAlert,
  ShieldCheck,
  ShoppingCart,
  Sliders,
  Smartphone,
  StickyNote,
  Store,
  Tag,
  Ticket,
  Trash2,
  TrendingUp,
  Trophy,
  Truck,
  Unlock,
  User,
  UserMinus,
  UserPlus,
  UserRound,
  Users,
  Webhook,
  X,
  XCircle,
} from 'lucide-react'

export const LUCIDE_ICON_REGISTRY: Record<string, LucideIcon> = {
  'alert-circle': AlertCircle,
  'alert-triangle': AlertTriangle,
  'badge-check': BadgeCheck,
  'bar-chart-2': BarChart2,
  'bell': Bell,
  'bolt': Bolt,
  'box': Box,
  'briefcase': Briefcase,
  'briefcase-business': BriefcaseBusiness,
  'building': Building,
  'building2': Building2,
  'calendar': Calendar,
  'calendar-check': CalendarCheck,
  'calendar-clock': CalendarClock,
  'calendar-off': CalendarOff,
  'calendar-x': CalendarX,
  'check': Check,
  'check-circle': CheckCircle,
  'check-square': CheckSquare,
  'clipboard-list': ClipboardList,
  'clock': Clock,
  'clock-3': Clock3,
  'coins': Coins,
  'copy': Copy,
  'credit-card': CreditCard,
  'database': Database,
  'dollar-sign': DollarSign,
  'download': Download,
  'external-link': ExternalLink,
  'file-minus': FileMinus,
  'file-text': FileText,
  'filter-x': FilterX,
  'folder-tree': FolderTree,
  'git-branch': GitBranch,
  'git-compare-arrows': GitCompareArrows,
  'git-pull-request-arrow': GitPullRequestArrow,
  'handshake': Handshake,
  'heart': Heart,
  'inbox': Inbox,
  'key': Key,
  'key-round': KeyRound,
  'layers': Layers,
  'line-chart': LineChart,
  'list': List,
  'lock': Lock,
  'mail': Mail,
  'mail-open': MailOpen,
  'map-pin': MapPin,
  'package': Package,
  'package-plus': PackagePlus,
  'package-x': PackageX,
  'percent': Percent,
  'pie-chart': PieChart,
  'plus-square': PlusSquare,
  'receipt': Receipt,
  'receipt-text': ReceiptText,
  'reply': Reply,
  'ruler': Ruler,
  'settings': Settings,
  'shapes': Shapes,
  'shield': Shield,
  'shield-alert': ShieldAlert,
  'shield-check': ShieldCheck,
  'shopping-cart': ShoppingCart,
  'sliders': Sliders,
  'smartphone': Smartphone,
  'sticky-note': StickyNote,
  'store': Store,
  'tag': Tag,
  'ticket': Ticket,
  'trash-2': Trash2,
  'trending-up': TrendingUp,
  'trophy': Trophy,
  'truck': Truck,
  'unlock': Unlock,
  'user': User,
  'user-minus': UserMinus,
  'user-plus': UserPlus,
  'user-round': UserRound,
  'users': Users,
  'webhook': Webhook,
  'x': X,
  'x-circle': XCircle,
}

function normalizeKebabIconName(input: string): string {
  const trimmed = input.trim()
  if (!trimmed) return ''
  if (!trimmed.includes('-') && !trimmed.includes('_') && !trimmed.includes(' ') && /[A-Z]/.test(trimmed)) {
    return trimmed
      .replace(/([a-z0-9])([A-Z])/g, '$1-$2')
      .replace(/([A-Z])([A-Z][a-z])/g, '$1-$2')
      .toLowerCase()
  }
  return trimmed
    .replace(/[_\s]+/g, '-')
    .replace(/-+/g, '-')
    .toLowerCase()
}

export function resolveRegisteredLucideIcon(name: string | undefined): LucideIcon | null {
  if (!name) return null
  const normalized = normalizeKebabIconName(name)
  if (!normalized) return null
  return (LUCIDE_ICON_REGISTRY as Record<string, LucideIcon | undefined>)[normalized] ?? null
}

export function resolveRegisteredLucideIconNode(
  name: string | undefined,
  className: string
): React.ReactNode | null {
  const Icon = resolveRegisteredLucideIcon(name)
  if (!Icon) return null
  return <Icon className={className} />
}
