#!/usr/bin/env bash
set -euo pipefail

# Generates docker-compose.volumes.yml with a named volume for every
# packages/*/dist directory. Runs on the HOST via initializeCommand
# so new packages are picked up automatically — no manual edits needed.

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
ROOT_DIR="$(cd "$SCRIPT_DIR/../.." && pwd)"
OUTPUT="$SCRIPT_DIR/../docker-compose.volumes.yml"

volume_mounts=""
volume_declarations=""

for pkg_dir in "$ROOT_DIR"/packages/*/; do
  [ -d "$pkg_dir" ] || continue
  pkg_name="$(basename "$pkg_dir")"
  # Normalize name for Docker volume (replace hyphens with underscores)
  vol_name="pkg_${pkg_name//-/_}_dist"

  volume_mounts="$volume_mounts      - ${vol_name}:/workspace/packages/${pkg_name}/dist
"
  volume_declarations="$volume_declarations  ${vol_name}:
"
done

cat > "$OUTPUT" <<EOF
# Auto-generated by generate-compose-volumes.sh — do not edit manually.
# Regenerated each time the container starts (via initializeCommand).
# Creates a named volume for every packages/*/dist directory so that
# Docker bind mounts don't overwrite container builds with empty host dirs.

services:
  workspace:
    volumes:
${volume_mounts}
volumes:
${volume_declarations}
EOF

echo "Generated $OUTPUT with dist volumes for $(echo "$volume_declarations" | grep -c ':') packages."

# --- Generate default docker-compose.local.yml if it doesn't exist ---
LOCAL_OVERRIDE="$SCRIPT_DIR/../docker-compose.local.yml"
if [ ! -f "$LOCAL_OVERRIDE" ]; then
  cat > "$LOCAL_OVERRIDE" <<'LOCALEOF'
# Personal overrides — gitignored, never committed.
# Add extra bind mounts, env vars, or services here.
#
# Example: mount a sibling repo into the container
#
# services:
#   workspace:
#     volumes:
#       - ../../my-other-repo:/workspace/.external/my-other-repo:cached

services: {}
LOCALEOF
  echo "Created default $LOCAL_OVERRIDE (customize for your local setup)."
fi
