import type { NotificationTypeDefinition } from '@open-mercato/shared/modules/notifications/types'

export const notificationTypes: NotificationTypeDefinition[] = [
  {
    type: 'record_locks.participant.joined',
    module: 'record_locks',
    titleKey: 'record_locks.notifications.participant_joined.title',
    bodyKey: 'record_locks.notifications.participant_joined.body',
    icon: 'users',
    severity: 'info',
    actions: [],
    expiresAfterHours: 24,
  },
  {
    type: 'record_locks.participant.left',
    module: 'record_locks',
    titleKey: 'record_locks.notifications.participant_left.title',
    bodyKey: 'record_locks.notifications.participant_left.body',
    icon: 'user-minus',
    severity: 'info',
    actions: [],
    expiresAfterHours: 24,
  },
  {
    type: 'record_locks.lock.contended',
    module: 'record_locks',
    titleKey: 'record_locks.notifications.lock_contended.title',
    bodyKey: 'record_locks.notifications.lock_contended.body',
    icon: 'users',
    severity: 'warning',
    actions: [],
    expiresAfterHours: 48,
  },
  {
    type: 'record_locks.lock.force_released',
    module: 'record_locks',
    titleKey: 'record_locks.notifications.lock_force_released.title',
    bodyKey: 'record_locks.notifications.lock_force_released.body',
    icon: 'unlock',
    severity: 'warning',
    actions: [],
    expiresAfterHours: 48,
  },
  {
    type: 'record_locks.record.deleted',
    module: 'record_locks',
    titleKey: 'record_locks.notifications.record_deleted.title',
    bodyKey: 'record_locks.notifications.record_deleted.body',
    icon: 'trash-2',
    severity: 'warning',
    actions: [],
    expiresAfterHours: 48,
  },
  {
    type: 'record_locks.conflict.detected',
    module: 'record_locks',
    titleKey: 'record_locks.notifications.conflict_detected.title',
    bodyKey: 'record_locks.notifications.conflict_detected.body',
    icon: 'git-compare-arrows',
    severity: 'warning',
    actions: [],
    expiresAfterHours: 48,
  },
  {
    type: 'record_locks.incoming_changes.available',
    module: 'record_locks',
    titleKey: 'record_locks.notifications.incoming_changes.title',
    bodyKey: 'record_locks.notifications.incoming_changes.body',
    icon: 'git-pull-request-arrow',
    severity: 'info',
    actions: [],
    expiresAfterHours: 48,
  },
  {
    type: 'record_locks.conflict.resolved',
    module: 'record_locks',
    titleKey: 'record_locks.notifications.conflict_resolved.title',
    bodyKey: 'record_locks.notifications.conflict_resolved.body',
    icon: 'check-circle',
    severity: 'info',
    actions: [],
    expiresAfterHours: 48,
  },
]

export default notificationTypes
