import type { SourceFile, WriterFunction } from 'ts-morph'
import {
  addAutoGeneratedComment,
  addImportSpecs,
  arrayLiteral,
  asExpression,
  arrowFunction,
  binaryExpression,
  nullishCoalesce,
  elementAccess,
  forOfStatement,
  identifier,
  ifStatement,
  importExpression,
  invokeImmediately,
  objectLiteral,
  parenthesized,
  propertyAccess,
  returnStatement,
  variableStatement,
  writeValue,
  createGeneratedSourceFile,
  getSourceText,
  type GeneratedImportSpec,
  type GeneratedObjectEntry,
} from '../ast'

export function renderGeneratedTsSource(options: {
  fileName: string
  imports?: GeneratedImportSpec[]
  build: (sourceFile: SourceFile) => void
  generator?: string
}): string {
  const { fileName, imports = [], build, generator = 'registry' } = options
  const sourceFile = createGeneratedSourceFile(fileName)

  addAutoGeneratedComment(sourceFile, generator)
  addImportSpecs(sourceFile, imports)
  build(sourceFile)

  return getSourceText(sourceFile)
}

export function namespaceImportSpec(name: string, moduleSpecifier: string): GeneratedImportSpec {
  return {
    namespaceImport: name,
    moduleSpecifier,
  }
}

export function defaultImportSpec(name: string, moduleSpecifier: string): GeneratedImportSpec {
  return {
    defaultImport: name,
    moduleSpecifier,
  }
}

export function sideEffectImportSpec(moduleSpecifier: string): GeneratedImportSpec {
  return {
    moduleSpecifier,
  }
}

export function namespaceMember(importName: string, memberName: string): WriterFunction {
  return propertyAccess(identifier(importName), memberName)
}

export function parenthesizedNamespaceMember(importName: string, memberName: string): WriterFunction {
  return parenthesized(namespaceMember(importName, memberName))
}

export function fallbackChain(expressions: WriterFunction[]): WriterFunction {
  return nullishCoalesce(expressions)
}

export function namespaceFallback(options: {
  importName: string
  members: string[]
  fallback: WriterFunction
  castType?: string
}): WriterFunction {
  const expression = invokeImmediately(
    arrowFunction({
      body: (writer) => {
        writer.block(() => {
          forOfStatement({
            variable: 'key',
            iterable: arrayLiteral(options.members, writeValue),
            statements: [
              variableStatement({
                name: 'candidate',
                initializer: elementAccess(
                  asExpression(identifier(options.importName), 'Record<string, unknown>'),
                  identifier('key'),
                ),
              }),
              ifStatement({
                condition: binaryExpression(identifier('candidate'), '!=', null),
                thenStatements: [returnStatement(identifier('candidate'))],
              }),
            ],
          })(writer)
          writer.newLine()
          returnStatement(options.fallback)(writer)
        })
      },
    }),
  )

  if (!options.castType) {
    return expression
  }

  return asExpression(expression, options.castType)
}

export function emptyArray(): WriterFunction {
  return arrayLiteral([], writeValue)
}

export function emptyObject(): WriterFunction {
  return objectLiteral([])
}

export function moduleEntry(
  moduleId: string,
  entries: Array<GeneratedObjectEntry>,
): WriterFunction {
  return objectLiteral([
    { name: 'moduleId', value: moduleId },
    ...entries,
  ])
}

export function dynamicImportExpression(moduleSpecifier: string): WriterFunction {
  return importExpression(moduleSpecifier)
}
