import { ContentLayout } from '../components/ContentLayout'

export default function TermsPage() {
  return (
    <ContentLayout
      title="Terms of Service"
      intro="Effective as of January 1, 2026"
      breadcrumb={[
        { label: 'Home', href: '/' },
        { label: 'Terms of Service' },
      ]}
    >
      <p>
        <strong>These Terms of Service</strong> (&ldquo;Terms&rdquo;) govern temporary, free-of-charge access to the hosted
        software platform operated by <strong>CT Tornado</strong> sp. z o.o., a company duly incorporated and existing under
        the laws of the Republic of Poland, with its principal place of business in Wroclaw (address: ul. Wyspa S&#322;odowa 7,
        50-266 Wroclaw, Poland; registration: District Court for Wroc&#322;aw-Fabryczna in Wroclaw, company no.: 873910;
        EU VAT no.: PL8982262377; share capital: PLN 5,000.00; email address:{' '}
        <a href="mailto:info@catchthetornado.com">info@catchthetornado.com</a>;
        &ldquo;<strong>CTT</strong>&rdquo;, &ldquo;we&rdquo;, &ldquo;us&rdquo;, and the like) and available at{' '}
        <a href="https://demo.openmercato.com" target="_blank" rel="noreferrer">demo.openmercato.com</a>{' '}
        (the &ldquo;<strong>Platform</strong>&rdquo;).
      </p>
      <p>
        By creating an Account, accessing, or using the Platform, you (the &ldquo;<strong>Customer</strong>&rdquo;,
        &ldquo;you&rdquo;, and the like) acknowledge and agree that: (i) the Services are provided gratuitously (without
        remuneration); (ii) use is limited to internal evaluation of the Platform&rsquo;s functionality; and (iii) CTT may
        modify, restrict, or discontinue the Services at any time, without notice or liability.
      </p>
      <p>
        The Platform is provided solely for demonstration, testing, and evaluation purposes, not for production, operational,
        or commercial use. To deploy the Platform in a production or commercial environment, a separate paid agreement with
        CTT is required.
      </p>

      <h2>1. Definitions</h2>
      <p>For the purposes of these Terms, the following expressions have the meanings set out below:</p>
      <ul>
        <li>&ldquo;<strong>Account</strong>&rdquo; means the Customer&rsquo;s administrative account through which its Authorized Users access the Services.</li>
        <li>&ldquo;<strong>Authorized User</strong>&rdquo; means any individual whom the Customer authorizes to use the Services under its Account.</li>
        <li>&ldquo;<strong>Platform</strong>&rdquo; means the modular, multi-tenant software framework operated by CTT, comprising the core runtime, directory, modules, APIs, events, workflows, and configuration interfaces enabling Customers to build and operate business applications.</li>
        <li>&ldquo;<strong>Module</strong>&rdquo; means a separately deployable component that may add pages, APIs, entities, forms, validators, or workflows within the Platform.</li>
        <li>&ldquo;<strong>Tenant</strong>&rdquo; means a logically isolated environment within the Platform, associated with one Customer Organization and its Authorized Users.</li>
        <li>&ldquo;<strong>Customer Organization</strong>&rdquo; means a structural unit within a Tenant defining visibility scopes and role hierarchies.</li>
        <li>&ldquo;<strong>Customer Data</strong>&rdquo; means all data and content submitted to or collected through the Services within the Tenant(s), including data stored in custom entities and forms.</li>
        <li>&ldquo;<strong>Configuration Data</strong>&rdquo; means schemas, dynamic forms, role mappings, feature flags, workflows, and metadata created by the Customer within its Tenant(s).</li>
        <li>&ldquo;<strong>Service Data</strong>&rdquo; means telemetry, diagnostics, and operational data generated by the Platform in connection with the Customer&rsquo;s use of the Services.</li>
        <li>&ldquo;<strong>Generated Output</strong>&rdquo; content or materials produced by the Services for the Customer, including AI-assisted or automated results, if such functionality is enabled in the Demo Environment.</li>
        <li>&ldquo;<strong>Demo Environment</strong>&rdquo; means a hosted, non-production environment made available for temporary demonstration, testing, and evaluation purposes only.</li>
        <li>&ldquo;<strong>Services</strong>&rdquo; means the temporary, free-of-charge access to the Platform provided by CTT through the Demo Environment, including related interfaces and features necessary to enable such access. The Services exclude production environments, support, maintenance, and any paid functionality.</li>
      </ul>

      <h2>2. Scope of Services</h2>
      <p>
        <strong>(a) Purpose and Nature.</strong> The Services consist of hosted access to the Platform made available by CTT
        free of charge for demonstration, testing, and evaluation purposes only. The Platform&rsquo;s general description,
        features, and technical documentation are available at{' '}
        <a href="https://docs.openmercato.com" target="_blank" rel="noreferrer">https://docs.openmercato.com</a>.
        The Customer should evaluate the Platform&rsquo;s suitability using professional judgment. The Services are not
        intended or licensed for production, operational, or commercial deployment.
      </p>
      <p>
        <strong>(b) Temporary and Revocable Access.</strong> Access to the Services is temporary, non-exclusive, and revocable
        at any time at CTT&rsquo;s discretion. CTT may limit, modify, or discontinue the Services, in whole or in part,
        without prior notice and without any obligation to maintain continuity or data persistence.
      </p>
      <p>
        <strong>(c) Availability and Performance.</strong> CTT does not guarantee uninterrupted operation, performance, or
        error-free functionality of the Services. No service levels, backups, or restoration obligations apply. The Services
        are provided on a testing basis only and are subject to the limitations, disclaimers, and liability exclusions set out
        in Sections 15 and 16.
      </p>
      <p>
        <strong>(d) Transition to Commercial Use.</strong> To continue using the Platform beyond the demonstration period or
        for production purposes, the Customer must enter into a separate, paid subscription or service agreement with CTT, if
        available. Any continued use after CTT withdraws free-of-charge access is unauthorized.
      </p>

      <h2>3. Formation of Agreement</h2>
      <p>
        <strong>(a) Method of Acceptance.</strong> A contract for the provision of the Services (the &ldquo;<strong>Agreement</strong>&rdquo;)
        is concluded upon the earlier of: (i) the Customer&rsquo;s acceptance of these Terms through an online registration
        form available at{' '}
        <a href="https://demo.openmercato.com/onboarding" target="_blank" rel="noreferrer">demo.openmercato.com/onboarding</a>,
        checkbox, or equivalent act; (ii) the Customer&rsquo;s signature or acceptance of an order form, quotation, or
        statement of work referring to these Terms; or (iii) the Customer&rsquo;s first access to or use of the Services.
      </p>
      <p>
        <strong>(b) Authority to Bind.</strong> The individual accepting or registering on behalf of a legal entity represents
        and warrants that they are duly authorized to bind that entity. CTT may rely on this representation in good faith
        until notified in writing that such authority has been withdrawn.
      </p>
      <p>
        <strong>(c) Contracting Entity.</strong> Where registration identifies a company or other legal entity, the Agreement
        is deemed concluded with that entity, even if registration was performed using an individual&rsquo;s contact data.
      </p>
      <p>
        <strong>(d) Entire Agreement for Demo Access.</strong> A purchase order, statement of work, or similar document issued
        or referenced by the Customer may serve as confirmation of the Customer&rsquo;s intent to access the Platform under
        these Terms. However, no such document modifies, supplements, or prevails over these Terms, even if acknowledged or
        referenced by CTT. These Terms constitute the sole and exclusive legal framework governing access to and use of the
        Platform through the Demo Environment.
      </p>

      <h2>4. Technical and Operational Requirements</h2>
      <p>
        <strong>(a) Minimum Requirements.</strong> To access and use the Services, the Customer must ensure: (i) reliable
        Internet connectivity and compatible hardware; (ii) use of a supported browser (current versions of Chrome, Firefox,
        Safari, or Edge) or another interface designated by CTT; (iii) configuration of network and security settings that
        permit encrypted HTTPS communication; and (iv) use of secure authentication methods and strong passwords or
        multifactor authentication where available.
      </p>
      <p>
        <strong>(b) Customer Responsibility.</strong> The Customer is solely responsible for maintaining the systems, networks,
        and devices necessary to connect to the Services and for compliance with applicable security and data-protection laws.
      </p>
      <p>
        <strong>(c) Compatibility Disclaimer.</strong> CTT does not guarantee compatibility with any specific operating system,
        hardware, or third-party software unless expressly confirmed in writing.
      </p>
      <p>
        <strong>(d) API Access.</strong> Access to APIs requires active credentials issued by CTT. CTT may modify technical
        specifications or deprecate interfaces upon reasonable notice, as provided in Section 9.
      </p>

      <h2>5. Accounts, Tenants, and Access Control</h2>
      <p>
        <strong>(a) Account Administration.</strong> The Account serves as the administrative environment through which its
        Authorized Users access the Services. The Customer designates at least one administrator responsible for creating,
        managing, and deactivating Authorized Users.
      </p>
      <p>
        <strong>(b) Tenant Isolation.</strong> CTT maintains logical isolation between Tenants to prevent cross-tenant access
        to Customer Data. CTT&rsquo;s responsibility for data segregation is limited to the technical controls within the
        Platform. Any intentional connection, integration, or data sharing between Tenants is performed at the Customer&rsquo;s
        sole discretion and risk.
      </p>
      <p>
        <strong>(c) Roles, Permissions, and Feature Access.</strong> The Services include role-based access control and
        feature-flag mechanisms. CTT provides the means for configuration, but the Customer determines which roles and
        permissions are granted to its Authorized Users. CTT is not responsible for losses or unauthorized access resulting
        from misconfiguration by the Customer.
      </p>
      <p>
        <strong>(d) Security of Credentials.</strong> The Customer must ensure that login credentials and API keys are used
        only by duly authorized persons and are stored securely. Compromised credentials must be revoked immediately. CTT may
        suspend access in case of suspected compromise.
      </p>
      <p>
        <strong>(e) Compliance and Monitoring.</strong> The Customer is responsible for monitoring its users&rsquo; activity
        within its Tenant and for ensuring compliance with these Terms and applicable law. CTT is not obliged to supervise
        individual user actions unless required by law or agreed in writing.
      </p>

      <h2>6. Fees and Payment</h2>
      <p>
        <strong>(a) No Fees.</strong> The Services are provided free of charge. CTT makes no claim to remuneration, and the
        Customer incurs no payment obligation for use governed by these Terms.
      </p>
      <p>
        <strong>(b) No Implied Consideration or Renewal.</strong> The gratuitous nature of the Services excludes any implied
        continuation, renewal, or conversion to a paid relationship. CTT&rsquo;s temporary provision of access does not
        create any entitlement to future availability or preferential terms for paid services.
      </p>
      <p>
        <strong>(c) Taxes and Charges.</strong> As no fees are payable, no taxes or public charges arise. If the Customer&rsquo;s
        use of the Services nonetheless triggers any tax liability under applicable law, such liability rests solely with the
        Customer.
      </p>
      <p>
        <strong>(d) Withdrawal of Access.</strong> CTT may suspend or terminate access to the Services at any time, without
        notice and without liability of any kind, including for loss of data or functionality.
      </p>

      <h2>7. Acceptable Use</h2>
      <p>
        The Customer and its Authorized Users must not: (i) use the Services for unlawful purposes or in a manner infringing
        third-party rights; (ii) interfere with or attempt to compromise the Platform&rsquo;s security, performance, or
        stability; (iii) circumvent technical limits or rate restrictions; (iv) resell or make the Services available to third
        parties except as expressly permitted; or (v) rely on the Services for high-risk activities where failure could cause
        injury, death, or significant damage.
      </p>

      <h2>8. Intellectual Property and Custom Components</h2>
      <p>
        <strong>(a) Ownership of the Platform and Related Materials.</strong> The underlying Open Mercato project is
        distributed under the MIT License, and its contributors have licensed their respective contributions to the public
        under that license. CTT uses the Platform in accordance with those rights. CTT retains ownership of: (i) all
        proprietary modifications, configurations, integrations, and deployment materials it creates or applies in connection
        with the hosted demo environment; (ii) all Service Data, documentation, and content made available by CTT; and
        (iii) any proprietary modules, components, or extensions independently developed by CTT. CTT provides access to the
        hosted instance of the Platform under these proprietary Terms, which govern the Customer&rsquo;s use of the Services.
        These Terms do not alter or limit the rights granted under the MIT License for the open-source version of Open Mercato
        available through its public repository.
      </p>
      <p>
        <strong>(b) Customer Data, Generated Output, and Customer Modules.</strong> The Customer retains ownership of its
        Customer Data and any Generated Output produced through the Services. If the Demo Environment allows the Customer to
        create or upload its own modules, those modules and their underlying code remain the Customer&rsquo;s intellectual
        property. The Customer grants CTT a non-exclusive, worldwide, royalty-free license to host, execute, and display such
        modules within the Demo Environment for the duration of the Services. CTT is not required to review, maintain, or
        preserve Customer Modules and may delete or disable them at any time without notice. Because the Services are temporary
        and provided for demonstration only, all Customer Data, Generated Output, and any Customer Modules may be deleted at
        any time in accordance with Section 10.
      </p>
      <p>
        <strong>(c) Limited Right to Access the Hosted Environment.</strong> CTT grants the Customer a personal, non-exclusive,
        non-transferable, revocable right to access and use the hosted instance of the Platform provided through the Demo
        Environment solely for internal evaluation. This right does not limit or restrict any rights the Customer may have
        under the MIT License with respect to the open-source version of the Platform available from its public repository.
        The Customer must not interfere with, copy, extract, or reproduce the hosted environment, its configuration, or
        CTT&rsquo;s proprietary components, integrations, or branding.
      </p>
      <p>
        <strong>(d) Configuration Data and Feedback.</strong> CTT may collect and use Configuration Data and any feedback or
        suggestions provided by the Customer to improve or develop the Platform. CTT receives a perpetual, worldwide,
        royalty-free license to use such feedback and configuration information for these purposes, provided it does not
        identify the Customer.
      </p>
      <p>
        <strong>(e) Third-Party Components.</strong> The Platform may include or interoperate with third-party libraries, APIs,
        or services subject to their own license terms. CTT is not responsible for third-party content, performance, or
        availability.
      </p>

      <h2>9. APIs, Events, and Integrations</h2>
      <p>
        <strong>(a) API and Integration Access.</strong> The Services may expose APIs and webhooks for testing integrations or
        automation. CTT may modify, restrict, or disable such access at any time without notice. API keys or credentials
        issued to the Customer must be kept secure and used only within the Demo Environment.
      </p>
      <p>
        <strong>(b) Events and Delivery.</strong> The Platform may generate events or webhooks as part of its demonstration
        features. Delivery, order, or timing of such events is not guaranteed. The Customer&rsquo;s receiving systems must
        tolerate delays, retries, or interruptions.
      </p>
      <p>
        <strong>(c) External Connections.</strong> If the Customer connects the Demo Environment to any external or third-party
        system, it does so at its own risk. CTT is not responsible for data transmitted to or from third-party services or for
        their behavior, security, or availability.
      </p>

      <h2>10. Data Handling, Export, and Deletion</h2>
      <p>
        <strong>(a) Nature of Demo Data.</strong> Demo Data is processed solely to enable demonstration and testing of the
        Platform&rsquo;s functionality. The Customer should not use the Services to process production data, personal data, or
        confidential information.
      </p>
      <p>
        <strong>(b) Automatic Deletion and Rotation.</strong> Demo Data is not retained on a permanent basis. CTT may
        automatically delete, anonymize, or replace all Demo Data at any time, typically every twenty-four (24) hours, without
        notice. No backups are performed, and no recovery or restoration is available.
      </p>
      <p>
        <strong>(c) No Export Rights.</strong> The Customer has no right or expectation to export, retrieve, or access Demo
        Data after deletion. CTT is under no obligation to provide data extracts, confirmations of deletion, or destruction
        certificates.
      </p>
      <p>
        <strong>(d) Termination of Access.</strong> Upon discontinuation of the Services&mdash;whether by CTT or the
        Customer&mdash;all Demo Data may be deleted immediately and permanently without liability.
      </p>

      <h2>11. Operational Commitments</h2>
      <p>
        <strong>(a) General Approach.</strong> CTT maintains commercially reasonable administrative, technical, and physical
        safeguards designed to protect the integrity and security of the Platform.
      </p>
      <p>
        <strong>(b) No Service Levels.</strong> Given the demonstrative nature of the Services, CTT provides no uptime,
        response-time, or performance commitments. The Services may be interrupted, modified, or discontinued at any time
        without notice.
      </p>
      <p>
        <strong>(c) Updates and Maintenance.</strong> CTT may deploy updates, perform maintenance, or change configurations at
        any time to enhance or test the functionality, security, or performance of the Platform. Such actions may result in
        temporary unavailability or loss of Demo Data.
      </p>
      <p>
        <strong>(d) Complaints Procedure.</strong> The Customer may submit technical or operational complaints regarding the
        Services by email to <a href="mailto:info@catchthetornado.com">info@catchthetornado.com</a> or through any channel
        designated by CTT. Complaints must specify the nature of the issue, its impact, and, where applicable, supporting
        details such as timestamps or screenshots. CTT will review complaints in good faith and may, at its sole discretion,
        provide explanations, guidance, or corrective actions. Submission of a complaint does not create any entitlement to
        remedy, compensation, or continued access to the Services.
      </p>

      <h2>12. Suspension and Termination</h2>
      <p>
        <strong>(a) CTT&rsquo;s Right to Suspend or Terminate.</strong> CTT may suspend or terminate the Customer&rsquo;s
        access to the Services, in whole or in part, at any time and for any reason, including maintenance, misuse of the
        Services, or compliance with legal requirements. No prior notice is required.
      </p>
      <p>
        <strong>(b) Customer&rsquo;s Right to Discontinue Use.</strong> The Customer may cease using the Services at any time
        by deleting its Account or otherwise discontinuing access.
      </p>
      <p>
        <strong>(c) Effect of Termination.</strong> Upon termination or suspension, all rights granted under these Terms
        immediately cease. All Demo Data may be deleted as provided in Section 10. CTT has no obligation to retain, deliver,
        or restore any data or configuration.
      </p>
      <p>
        <strong>(d) No Refunds or Compensation.</strong> Because the Services are provided free of charge, the Customer is not
        entitled to any refund, compensation, or continuation of access after termination.
      </p>

      <h2>13. Data Protection and Sub-Processors</h2>
      <p>
        <strong>(a) Limited Processing of Personal Data.</strong> CTT may process limited personal data, such as identifiers,
        contact details, or technical metadata, to enable Customer registration, authentication, telemetry, and general
        operation of the Services. Such processing is minimal and incidental to providing the Demo Environment. Details of
        CTT&rsquo;s processing of personal data&mdash;including categories of processed data, retention periods, user rights,
        and the hosting or infrastructure providers involved in supporting the Services&mdash;are set out in CTT&rsquo;s{' '}
        <a href="/privacy">Privacy Policy</a>. The Privacy Policy forms an informative supplement to these Terms but does not
        alter their contractual nature.
      </p>
      <p>
        <strong>(b) Customer Data.</strong> The Services are not intended for processing production data or special categories
        of personal data within the meaning of Article 9 GDPR. The Customer should not upload or submit such data to the
        Services.
      </p>
      <p>
        <strong>(c) Roles of the Parties.</strong> For personal data processed in connection with Account setup, telemetry, or
        Platform operation, CTT acts as a data controller. The Customer acts as an independent controller for any data it
        inputs into the Demo Environment. The parties do not act as joint controllers.
      </p>
      <p>
        <strong>(d) Contingent Processing as Processor.</strong> If, in connection with the Services, CTT processes personal
        data on behalf of (or as subcontracted by) the Customer, this Section 13(d) constitutes the data processing addendum
        (the &ldquo;<strong>DPA</strong>&rdquo;) between the parties within the meaning of Article 28 of the General Data
        Protection Regulation (the &ldquo;<strong>GDPR</strong>&rdquo;). The DPA becomes automatically applicable when CTT
        acts as a processor (or subprocessor) and governs such processing without the need for any separate written agreement.
        Under the DPA, CTT: (i) processes personal data&mdash;including names, contact details, and business information of
        the Customer&rsquo;s personnel, clients, or suppliers&mdash;only on documented instructions from the Customer and
        solely for the purpose and scope necessary to perform the Agreement; (ii) ensures that persons authorized to process
        such data are bound by confidentiality obligations; (iii) implements appropriate technical and organizational measures
        under Article 32 GDPR to ensure a level of security appropriate to the risk; (iv) may engage subprocessors, provided
        they are bound by confidentiality and security obligations no less protective than those imposed on CTT; (v) upon
        termination of the Services, deletes or returns the personal data to the Customer unless retention is required by law;
        (vi) promptly notifies the Customer of any personal-data breach and cooperates in fulfilling the obligations under
        Articles 33&ndash;36 GDPR; and (vii) upon request, makes available information necessary to demonstrate compliance
        with Article 28 GDPR, with any audits or inspections conducted on a schedule and in a manner that does not disrupt
        CTT&rsquo;s operations. In all cases, CTT processes personal data in accordance with applicable data-protection laws,
        including the GDPR.
      </p>

      <h2>14. Confidentiality and Security Obligations</h2>
      <p>
        <strong>(a) Confidential Information.</strong> Each party must protect the other&rsquo;s non-public information
        disclosed in connection with the Services and use it only as necessary to perform or evaluate the Service.
      </p>
      <p>
        <strong>(b) Exclusions.</strong> Information is not considered confidential if it: (i) becomes public without breach of
        these Terms; (ii) was lawfully known to the receiving party before disclosure; (iii) is independently developed without
        reference to the disclosing party&rsquo;s information; or (iv) is required to be disclosed by law or court order.
      </p>
      <p>
        <strong>(c) Security Notices.</strong> If the Customer becomes aware of a suspected security issue related to the
        Services, it should promptly notify CTT through the contact channel provided by CTT.
      </p>
      <p>
        <strong>(d) Survival.</strong> The confidentiality obligations under this Section survive discontinuation of the
        Services for a period of two (2) years, except for information qualifying as trade secrets, which remain protected as
        long as such information retains its confidential character.
      </p>

      <h2>15. Warranties and Disclaimers</h2>
      <p>
        <strong>(a) Authority.</strong> CTT represents that it has full right and authority to provide access to the Platform
        as described in these Terms.
      </p>
      <p>
        <strong>(b) No Other Warranties.</strong> Except for the representation in paragraph (a), the Services are provided
        &ldquo;as is&rdquo; and &ldquo;as available&rdquo;, without warranties or representations of any kind, whether
        express, implied, or statutory. CTT expressly disclaims all implied warranties, including merchantability, fitness for
        a particular purpose, satisfactory quality, title, and non-infringement.
      </p>
      <p>
        <strong>(c) No Continuity or Availability Commitment.</strong> CTT makes no guarantee that the Services or the
        Platform: (i) will be available at any particular time; (ii) will operate without interruption or error; or (iii) will
        maintain or preserve any data entered by the Customer. The Services may be modified, suspended, or discontinued at any
        time without notice.
      </p>
      <p>
        <strong>(d) No Reliance.</strong> The Customer acknowledges that it has not relied on any statements, descriptions, or
        performance metrics not expressly contained in these Terms. Access to and use of the Services are undertaken at the
        Customer&rsquo;s own risk and sole discretion.
      </p>
      <p>
        <strong>(e) Mandatory Law.</strong> Nothing in this Section excludes or limits any warranties or rights that cannot be
        excluded or limited under applicable law, including liability for willful misconduct, to the extent such exclusion
        would be invalid under Polish law.
      </p>

      <h2>16. Limitation of Liability</h2>
      <p>
        <strong>(a) General Rule and Cap.</strong> To the maximum extent permitted by law, CTT shall not be liable for any
        loss, damage, or claim arising out of or in connection with the use or inability to use the Services, including but not
        limited to loss of data, loss of profits, business interruption, reputational damage, or any indirect, incidental,
        special, punitive, or consequential losses, whether arising in contract, tort, or otherwise. Because the Services are
        provided free of charge, CTT&rsquo;s total aggregate liability for all claims under or in connection with these Terms
        shall in any event not exceed one hundred (100) Polish zlotys (PLN 100), representing a nominal allocation of risk
        proportionate to the non-remunerated nature of the arrangement.
      </p>
      <p>
        <strong>(b) Exclusions from Limitation.</strong> The limitations in this Section do not apply to: (i) liability for
        death or personal injury caused by willful misconduct; (ii) damages resulting from intentional breach of
        confidentiality obligations; or (iii) other liability that cannot be excluded under mandatory law.
      </p>
      <p>
        <strong>(c) Customer Responsibility.</strong> The Customer is solely responsible for any use of or reliance on the
        Services and for ensuring that no production, confidential, or personal data are introduced into the demo environment.
      </p>
      <p>
        <strong>(d) Force Majeure.</strong> Neither party is liable for any delay or failure to perform due to causes beyond
        its reasonable control, including natural disasters, war, governmental actions, or network failures.
      </p>

      <h2>17. Miscellaneous</h2>
      <p>
        <strong>(a) Publicity.</strong> CTT may include the Customer&rsquo;s name and logo in publicly available client lists,
        presentations, or informational materials identifying users of the Platform, provided such use does not imply
        endorsement. The Customer may withdraw consent for such use at any time by written notice, and CTT will remove the
        Customer&rsquo;s name or logo from future materials within a reasonable time.
      </p>
      <p>
        <strong>(b) Assignment.</strong> The Customer may not assign or transfer any rights or obligations under these Terms
        without CTT&rsquo;s prior written consent. CTT may assign or transfer these Terms, in whole or in part, including to
        an affiliate or lawful successor by merger, acquisition, or transfer of assets, without the Customer&rsquo;s consent.
      </p>
      <p>
        <strong>(c) Notices and Written Form.</strong> All notices must be in writing and delivered to the contact details
        provided in the parties&rsquo; respective accounts or as otherwise designated in writing. For the purposes of these
        Terms, and notwithstanding any stricter requirements under applicable law, the terms &ldquo;written&rdquo;, &ldquo;in
        writing&rdquo;, and similar expressions include communication made in a permanent form, such as email, provided that
        it allows the recipient to store the message and access it for future reference.
      </p>

      <h2>18. Final Provisions</h2>
      <p>
        <strong>(a) Governing Law and Jurisdiction.</strong> These Terms and any disputes arising out of or relating to them
        are governed by the laws of the Republic of Poland. The courts of Warsaw have exclusive jurisdiction over all such
        disputes.
      </p>
      <p>
        <strong>(b) Entire Agreement.</strong> These Terms and any referenced policies (such as the{' '}
        <a href="/privacy">Privacy Policy</a>) constitute the entire agreement between the parties concerning access to and
        use of the Services.
      </p>
      <p>
        <strong>(c) Severability.</strong> If any provision of these Terms is held invalid or unenforceable, the remaining
        provisions remain in full force and effect.
      </p>
      <p>
        <strong>(d) Waiver.</strong> A failure or delay in enforcing any right or provision under these Terms does not
        constitute a waiver of that right or provision.
      </p>
    </ContentLayout>
  )
}
