import type { CustomEntitySpec } from '@open-mercato/shared/modules/entities'
import { E } from '#generated/entities.ids.generated'

const systemEntities: CustomEntitySpec[] = [
  {
    id: E.sales.sales_order,
    label: 'Sales Order',
    description: 'Committed sales document that drives fulfillment and invoicing.',
    labelField: 'orderNumber',
    showInSidebar: false,
    fields: [],
  },
  {
    id: E.sales.sales_order_line,
    label: 'Sales Order Line',
    description: 'Individual line on a sales order, including product or service details.',
    labelField: 'name',
    showInSidebar: false,
    fields: [],
  },
  {
    id: E.sales.sales_order_adjustment,
    label: 'Sales Order Adjustment',
    description: 'Order-level adjustment representing promotions, taxes, or surcharges.',
    labelField: 'label',
    showInSidebar: false,
    fields: [],
  },
  {
    id: E.sales.sales_quote,
    label: 'Sales Quote',
    description: 'Pre-order offer shared with customers before confirmation.',
    labelField: 'quoteNumber',
    showInSidebar: false,
    fields: [],
  },
  {
    id: E.sales.sales_quote_line,
    label: 'Sales Quote Line',
    description: 'Line within a quote containing proposed products or services.',
    labelField: 'name',
    showInSidebar: false,
    fields: [],
  },
  {
    id: E.sales.sales_quote_adjustment,
    label: 'Sales Quote Adjustment',
    description: 'Quote-level adjustment capturing promotional or tax calculations.',
    labelField: 'label',
    showInSidebar: false,
    fields: [],
  },
  {
    id: E.sales.sales_invoice,
    label: 'Sales Invoice',
    description: 'Financial invoice derived from orders and shipments.',
    labelField: 'invoiceNumber',
    showInSidebar: false,
    fields: [],
  },
  {
    id: E.sales.sales_invoice_line,
    label: 'Sales Invoice Line',
    description: 'Line within an invoice referencing products or services billed.',
    labelField: 'description',
    showInSidebar: false,
    fields: [],
  },
  {
    id: E.sales.sales_payment,
    label: 'Sales Payment',
    description: 'Payment captured against orders or invoices.',
    labelField: 'paymentReference',
    showInSidebar: false,
    fields: [],
  },
  {
    id: E.sales.sales_payment_allocation,
    label: 'Sales Payment Allocation',
    description: 'Allocation mapping a payment to specific documents and amounts.',
    labelField: 'id',
    showInSidebar: false,
    fields: [],
  },
  {
    id: E.sales.sales_credit_memo,
    label: 'Sales Credit Memo',
    description: 'Credit memo issued for returns or adjustments.',
    labelField: 'creditMemoNumber',
    showInSidebar: false,
    fields: [],
  },
  {
    id: E.sales.sales_credit_memo_line,
    label: 'Sales Credit Memo Line',
    description: 'Line entry within a credit memo detailing refunded items or services.',
    labelField: 'description',
    showInSidebar: false,
    fields: [],
  },
  {
    id: E.sales.sales_shipment,
    label: 'Sales Shipment',
    description: 'Shipment record tracking dispatched packages for an order.',
    labelField: 'shipmentNumber',
    showInSidebar: false,
    fields: [],
  },
  {
    id: E.sales.sales_shipment_item,
    label: 'Sales Shipment Item',
    description: 'Line-level fulfillment record mapped to shipped quantities.',
    labelField: 'id',
    showInSidebar: false,
    fields: [],
  },
  {
    id: E.sales.sales_note,
    label: 'Sales Note',
    description: 'Internal or customer-facing note attached to a sales document.',
    labelField: 'body',
    showInSidebar: false,
    fields: [],
  },
]

export const entities = systemEntities
export default systemEntities
